### ISSUE TITLE
Regression: default playbooks missing for LXD driver

### ISSUE THREAD

**Issue by HalisCz** [ansible/molecule#1587] opened 2018-11-12 15:32 UTC
# Issue Type

- Bug report

# Molecule and Ansible details

```
ansible 2.7.1
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/user/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/user/.virtualenvs/nix-ansible/lib/python3.7/site-packages/ansible
  executable location = /home/user/.virtualenvs/nix-ansible/bin/ansible
  python version = 3.7.1 (default, Nov  5 2018, 14:07:04) [GCC 8.2.1 20181011 (Red Hat 8.2.1-4)]
molecule, version 2.19.0
```

Molecule installation method (one of):

- pip

Ansible installation method (one of):

- pip

Detail any linters or test runners used:

# Desired Behavior

After running `molecule init role --role-name basic_server --driver-name lxd`, there should be default playbooks as this:
```
basic_server
├── defaults
│   └── main.yml
├── handlers
│   └── main.yml
├── meta
│   └── main.yml
├── molecule
│   └── default
│       ├── tests
│       │   ├── __pycache__
│       │   │   └── test_default.cpython-37.pyc
│       │   └── test_default.py
│       ├── create.yml
│       ├── destroy.yml
│       ├── INSTALL.rst
│       ├── molecule.yml
│       ├── playbook.yml
│       └── prepare.yml
├── tasks
│   └── main.yml
├── vars
│   └── main.yml
└── README.md

9 directories, 14 files
```
This is working in `molecule==2.17` from pip.

# Actual Behaviour

Playbooks `create.yml`, `destroy.yml` and `prepare.yml` are missing.

```
basic_server
├── defaults
│   └── main.yml
├── handlers
│   └── main.yml
├── meta
│   └── main.yml
├── molecule
│   └── default
│       ├── tests
│       │   ├── __pycache__
│       │   │   └── test_default.cpython-37.pyc
│       │   └── test_default.py
│       ├── INSTALL.rst
│       ├── molecule.yml
│       └── playbook.yml
├── tasks
│   └── main.yml
├── vars
│   └── main.yml
└── README.md

9 directories, 11 files
```

**Comment by webknjaz** [comment] 2018-11-12 16:52
You call it a regression. What was the last version this worked as expected?

**Comment by HalisCz** [comment] 2018-11-12 16:54
> This is working in molecule==2.17 from pip.

**Comment by webknjaz** [comment] 2018-11-12 21:10
It looks like those files were removed via PR #1436.

**Comment by wilmardo** [comment] 2018-11-14 08:08
> After running molecule init role --role-name basic_server --driver-name lxd, there should be default playbooks as this

Nope ;)

Default playbooks are moved to [`molecule/provisioner/ansible/playbooks/<drivername>/`](https://github.com/ansible/molecule/tree/master/molecule/provisioner/ansible/playbooks) since Molecule V2. These playbooks are used unless you create a `create.yml` playbook in the scenario directory, this overrides the default `create.yml` in that directory.

For LXD I implemented this in the PR #1436 and it is available since Molecule v2.18.
This is the same behavior as Docker and Vagrant (and all the other when they get fixed ;))

**Comment by wilmardo** [comment] 2018-11-14 08:15
@webknjaz I try to keep updated with the Molecule issues but if needed tag me, especially LXD issues :)

**Comment by webknjaz** [comment] 2018-11-14 13:55
> Nope ;)

Why? If you keep those in the molecule resources, rather than a generated dir structure, the behavior may become unreproducible, because of Molecule upgrade and users would not expect such change of behavior.

**Comment by webknjaz** [comment] 2018-11-14 13:55
Is this documented?

**Comment by wilmardo** [comment] 2018-11-14 14:11
> Is this documented?

Yeah somewhat. It was implemented in #1278 and the documentation is found under [provisioner/ansible](https://molecule.readthedocs.io/en/latest/configuration.html#id12) in the docs:

```
The playbook loading order is:

    provisioner.playbooks.$driver_name.$action
    provisioner.playbooks.$action
    bundled_playbook.$driver_name.$action
```

> Why?

More then the above explanation by @retr0h in the PR I don't know.

I personally do not see that much of a problem as long as semver is correctly used. As I stated before for most users this resolves the whole problem of keeping all the playbooks in one place and DRY the roles. This without resulting in the use of submodules or gilt. 
Not keeping the playbooks up to date could also result in errors since the cerberus validation of Mocule changes or even the module upstream in Ansible.

I am interested in the view of the others though @dj-wasabi @lwm @gundalow :)

**Comment by webknjaz** [comment] 2018-11-14 15:06
fair enough

**Comment by webknjaz** [comment] 2018-11-17 13:46
@HalisCz does the info provided by @wilmardo suit you? May we close the issue now?

**Comment by HalisCz** [comment] 2018-12-27 12:57
@webknjaz I finally understand the motive behind these changes. Therefore, I consider this closed, although from the documentation piece

> The playbook loading order is:
       provisioner.playbooks.$driver_name.$action
       provisioner.playbooks.$action
       bundled_playbook.$driver_name.$action

I am not sure where to look for the default file. (I know just because I found out from PR #1278 )

**Closed** 2019-03-07 09:42 UTC
Labels: bug, help wanted
