### ISSUE TITLE
destroy steps do not run when tests fail and tags are used in provisioner options

### ISSUE THREAD

**Issue by dericcrago** [ansible/molecule#1906] opened 2019-04-08 03:21 UTC
# Issue Type

- Bug report

# Molecule and Ansible details

```
pipenv run ansible --version && pipenv run molecule --version
ansible 2.7.10
  config file = /Users/deric/.ansible.cfg
  configured module search path = ['/Users/deric/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/deric/.local/share/virtualenvs/molecule-destroy-cLlJrhaP/lib/python3.7/site-packages/ansible
  executable location = /Users/deric/.local/share/virtualenvs/molecule-destroy-cLlJrhaP/bin/ansible
  python version = 3.7.3 (default, Apr  7 2019, 11:57:41) [Clang 10.0.0 (clang-1000.11.45.5)]
molecule, version 2.20.1.dev18
```

Molecule installation method (one of):

- pipenv (see `Pipfile` in [example repo](https://github.com/dericcrago/molecule-destroy) and `README.md` for usage)

Ansible installation method (one of):

- pipenv (see `Pipfile` in [example repo](https://github.com/dericcrago/molecule-destroy) and `README.md` for usage)

Detail any linters or test runners used:

# Desired Behavior

Destroy steps run when tests fail and `tags` are used in `provisioner: options`.

# Actual Behaviour

Destroy steps do not run and PLAY RECAP details are missing when tests fail and `tags` are used in `provisioner: options`.

See [example repo](https://github.com/dericcrago/molecule-destroy).

```yaml
provisioner:
  name: ansible
  lint:
    name: ansible-lint
  options:
    tags: no-op
```

```
    PLAYBOOK: destroy.yml **********************************************************
    1 plays in /Users/deric/.local/share/virtualenvs/molecule-destroy-cLlJrhaP/src/molecule/molecule/provisioner/ansible/playbooks/docker/destroy.yml
    
    PLAY [Destroy] *****************************************************************
    META: ran handlers
    META: ran handlers
    META: ran handlers
    
    PLAY RECAP *********************************************************************
```

**Comment by decentral1se** [comment] 2019-04-09 07:03
Hi @dericcrago, can you please provide some more detailed logs? You can run molecule with `--debug` in order to look inot what molecule is failing on. Thanks.

**Comment by seandst** [comment] 2019-04-09 20:19
I cloned and used the reproducer. The destroy step runs, but the provisioner tags are applied so all of the destroy tasks appear to get filtered out, but only when destroy is run as a result of a failure in the test sequence.

Checking the debug output, the first (normal) destroy call in the test sequence runs `/path/to/bin/ansible-playbook --skip-tags=molecule-notest,notest --inventory=/tmp/molecule/molecule-destroy/default/inventory --diff /path/to/molecule/provisioner/ansible/playbooks/docker/destroy
.yml -vvv`

The second (on-error) destroy call runs `/path/to/bin/ansible-playbook --tags=no-op --skip-tags=molecule-notest,notest --inventory=/tmp/molecule/molecule-destroy/default/inventory --diff /path/to/molecule/provisioner/ansible/playbooks/docker/destroy.yml -vvv`

With a Mk. 1 eyeball diff, it looks like everything is the same with the exception of the addition of `--tags=no-op` in the on-error destroy call, which definitely shouldn't be there.

**Comment by seandst** [comment] 2019-04-09 20:27
I found the problem, and am putting together a PR now. I'm unable to assign this issue to myself, but would happily accept the assignment if anyone would like to do it for me. :)

**Comment by decentral1se** [comment] 2019-04-09 20:54
Solid stuff @seandst! 

cc @gundalow I think ^^^ is due the commit bit on this project :rocket: :rocket: :rocket:

**Comment by decentral1se** [comment] 2019-04-09 21:51
Hey @dericcrago, would be much appreciated if you have time to see if the change in https://github.com/ansible/molecule/pull/1913 works for you!

**Comment by seandst** [comment] 2019-04-09 22:31
I forgot to mention this in the PR, but I did test this with the reproducer in the issue and saw the desired behavior instead of the reported actual behavior.

**Comment by dericcrago** [comment] 2019-04-10 03:19
I can confirm that #1913 fixes this issue. Thank you @seandst & @decentral1se!

**Comment by seandst** [comment] 2019-04-10 17:14
That's great to hear! Thanks for testing it, and also thanks for the excellent reproducer.

**Closed** 2019-04-11 06:12 UTC
Labels: bug, pr-available
