### ISSUE TITLE
PY_COLORS fails with vagrant

### ISSUE THREAD

**Issue by Woytek-Polnik** [ansible/molecule#1881] opened 2019-03-26 17:56 UTC
# Issue Type

PY_COLORS does not perform as it was supposed to, it requires sudo.
Gitlab CI environment.

# Molecule and Ansible details

```
$ python -V
Python 2.7.5
$ molecule --version
molecule, version 2.20.0
$ ansible --version
ansible 2.7.8
```
   
Both installed with pip

# Log:
$ sudo molecule destroy -s libvirt
--> Validating schema /builds/test/molecule/libvirt/molecule.yml.
Validation completed successfully.
--> Test matrix
    
└── libvirt
    ├── cleanup
    └── destroy
    
--> Scenario: 'libvirt'
--> Action: 'cleanup'
Skipping, cleanup playbook not configured.
--> Scenario: 'libvirt'
--> Action: 'destroy'
    
    PLAY [Destroy] *****************************************************************
    
    TASK [Destroy molecule instance(s)] ********************************************
    ok: [localhost] => (item=None)
    ok: [localhost]
    
    TASK [Populate instance config] ************************************************
    ok: [localhost]
    
    TASK [Dump instance config] ****************************************************
    skipping: [localhost]
    
    PLAY RECAP *********************************************************************
    localhost                  : ok=2    changed=0    unreachable=0    failed=0
    
    
$ export PY_COLORS=0
$ molecule destroy -s libvirt
--> Validating schema /builds/test/molecule/libvirt/molecule.yml.
Validation completed successfully.
--> Test matrix
    
└── libvirt
    ├── cleanup
    └── destroy
    
--> Scenario: 'libvirt'
--> Action: 'cleanup'
Skipping, cleanup playbook not configured.
--> Scenario: 'libvirt'
--> Action: 'destroy'
    
    PLAY [Destroy] *****************************************************************
    
    TASK [Destroy molecule instance(s)] ********************************************
    ok: [localhost] => (item=None)
    ok: [localhost]
    
    TASK [Populate instance config] ************************************************
    ok: [localhost]
    
    TASK [Dump instance config] ****************************************************
    skipping: [localhost]
    
    PLAY RECAP *********************************************************************
    localhost                  : ok=2    changed=0    unreachable=0    failed=0
    
    
$ export PY_COLORS=1
$ molecule destroy -s libvirt
--> Validating schema /builds/test/molecule/libvirt/molecule.yml.
Validation completed successfully.
--> Test matrix
    
└── libvirt
    ├── cleanup
    └── destroy
    
--> Scenario: 'libvirt'
--> Action: 'cleanup'
Skipping, cleanup playbook not configured.
--> Scenario: 'libvirt'
--> Action: 'destroy'
    
    PLAY [Destroy] *****************************************************************
    
    TASK [Destroy molecule instance(s)] ********************************************
    failed: [localhost] (item=None) => {"censored": "the output has been hidden due to the fact that 'no_log: true' was specified for this result", "changed": false}
    fatal: [localhost]: FAILED! => {"censored": "the output has been hidden due to the fact that 'no_log: true' was specified for this result", "changed": false}
    
    PLAY RECAP *********************************************************************
    localhost                  : ok=0    changed=0    unreachable=0    failed=1   

# Detailed log

$ export PY_COLORS=1
$ molecule destroy -s libvirt
.
.
 failed: [localhost] (item={'box': u'centos/7', 'provider_options': {'memory': 1024, 'cpus': 1, 'uri': u"'qemu:///system'"}, 'name': u'centos7', 'groups': [u'centos']}) => {
        "changed": false, 
        "item": {
            "box": "centos/7", 
            "groups": [
                "centos"
            ], 
            "name": "centos7", 
            "provider_options": {
                "cpus": 1, 
                "memory": 1024, 
                "uri": "'qemu:///system'"
            }
        }, 
        "rc": 0
    }
    
    MSG:
    
    MODULE FAILURE
    See stdout/stderr for the exact error
    
    
    MODULE_STDOUT:
    
    --> Validating schema /builds/ansible/roles/molecule/libvirt/molecule.yml.
    Validation completed successfully.
    
    {"invocation": {"module_args": {"config_options": {}, "platform_box_url": null, "provider_cpus": 2, "provider_raw_config_args": null, "platform_box": "centos/7", "provider_override_args": null, "state": "destroy", "instance_interfaces": [], "instance_name": "centos7", "platform_box_version": null, "provider_memory": 512, "instance_raw_config_args": null, "provider_options": {"memory": 1024, "uri": "'qemu:///system'", "cpus": 1}, "provider_name": "libvirt", "provision": false, "force_stop": true}}, "changed": false}
    
    
    
    PLAY RECAP *********************************************************************
    localhost                  : ok=0    changed=0    unreachable=0    failed=1   

# Desired Behavior

I would like to use PY_COLORS fully without sudo.

# Actual Behaviour

Running as root in the container(gitlab CI executor), tested with privileged and without it. 
Everything worked with molecule 2.19. 
I updated to 2.20 and added PY_COLORS=1, now molecule create and destroy fails.
Adding sudo lets create and destroy pass through but the color disappears.

It could be somehow issued with gitlab Ci, but it keeps me wondering that with PY_COLORS=0 all works flawlessly.

**Comment by ssbarnea** [comment] 2019-03-26 18:03
Please run in debug mode and identify the problem, I personally do not find any link between an environment variable and the need to run sudo. The pasted logs are not providing any hints regarding what could have got run but `See stdout/stderr for the exact error` gives some hints.

**Comment by WojciechPolnik** [comment] 2019-03-26 18:10
personally debug didnt help me either

$ cd $CLONE_DIR
$ export PY_COLORS=1
$ molecule --debug destroy -s libvirt
--> Validating schema /builds/test/molecule/default/molecule.yml.
Validation completed successfully.
--> Validating schema /builds/test/molecule/libvirt/molecule.yml.
Validation completed successfully.
--> Test matrix
    
└── libvirt
    ├── cleanup
    └── destroy
    
--> Scenario: 'libvirt'
--> Action: 'cleanup'
Skipping, cleanup playbook not configured.
--> Scenario: 'libvirt'
--> Action: 'destroy'
DEBUG: ANSIBLE ENVIRONMENT
---
ANSIBLE_CONFIG: /tmp/molecule/test/libvirt/ansible.cfg
ANSIBLE_FILTER_PLUGINS: /usr/lib/python2.7/site-packages/molecule/provisioner/ansible/plugins/filters:/tmp/molecule/test/libvirt/plugins/filters:/builds/test/plugins/filters
ANSIBLE_FORCE_COLOR: 'true'
ANSIBLE_LIBRARY: /usr/lib/python2.7/site-packages/molecule/provisioner/ansible/plugins/libraries:/tmp/molecule/test/libvirt/library:/builds/test/library
ANSIBLE_ROLES_PATH: /tmp/molecule/test/libvirt/roles:/builds/wojciechpolnik

DEBUG: MOLECULE ENVIRONMENT
---
MOLECULE_DEBUG: 'True'
MOLECULE_DEPENDENCY_NAME: galaxy
MOLECULE_DRIVER_NAME: vagrant
MOLECULE_ENV_FILE: /builds/test/.env.yml
MOLECULE_EPHEMERAL_DIRECTORY: /tmp/molecule/test/libvirt
MOLECULE_FILE: /builds/test/molecule/libvirt/molecule.yml
MOLECULE_INSTANCE_CONFIG: /tmp/molecule/test/libvirt/instance_config.yml
MOLECULE_INVENTORY_FILE: /tmp/molecule/test/libvirt/inventory/ansible_inventory.yml
MOLECULE_LINT_NAME: yamllint
MOLECULE_PROJECT_DIRECTORY: /builds/test
MOLECULE_PROVISIONER_LINT_NAME: ansible-lint
MOLECULE_PROVISIONER_NAME: ansible
MOLECULE_SCENARIO_DIRECTORY: /builds/test/molecule/libvirt
MOLECULE_SCENARIO_NAME: libvirt
MOLECULE_VERIFIER_LINT_NAME: flake8
MOLECULE_VERIFIER_NAME: testinfra
MOLECULE_VERIFIER_TEST_DIRECTORY: /builds/test/molecule/libvirt/../shared/tests/

DEBUG: SHELL REPLAY
ANSIBLE_CONFIG=/tmp/molecule/test/libvirt/ansible.cfg ANSIBLE_FILTER_PLUGINS=/usr/lib/python2.7/site-packages/molecule/provisioner/ansible/plugins/filters:/tmp/molecule/test/libvirt/plugins/filters:/builds/test/plugins/filters ANSIBLE_FORCE_COLOR=true ANSIBLE_LIBRARY=/usr/lib/python2.7/site-packages/molecule/provisioner/ansible/plugins/libraries:/tmp/molecule/test/libvirt/library:/builds/test/library ANSIBLE_ROLES_PATH=/tmp/molecule/test/libvirt/roles:/builds/wojciechpolnik MOLECULE_DEBUG=True MOLECULE_DEPENDENCY_NAME=galaxy MOLECULE_DRIVER_NAME=vagrant MOLECULE_ENV_FILE=/builds/test/.env.yml MOLECULE_EPHEMERAL_DIRECTORY=/tmp/molecule/test/libvirt MOLECULE_FILE=/builds/test/molecule/libvirt/molecule.yml MOLECULE_INSTANCE_CONFIG=/tmp/molecule/test/libvirt/instance_config.yml MOLECULE_INVENTORY_FILE=/tmp/molecule/test/libvirt/inventory/ansible_inventory.yml MOLECULE_LINT_NAME=yamllint MOLECULE_PROJECT_DIRECTORY=/builds/test MOLECULE_PROVISIONER_LINT_NAME=ansible-lint MOLECULE_PROVISIONER_NAME=ansible MOLECULE_SCENARIO_DIRECTORY=/builds/test/molecule/libvirt MOLECULE_SCENARIO_NAME=libvirt MOLECULE_VERIFIER_LINT_NAME=flake8 MOLECULE_VERIFIER_NAME=testinfra MOLECULE_VERIFIER_TEST_DIRECTORY=/builds/test/molecule/libvirt/../shared/tests/

DEBUG: COMMAND
/usr/bin/ansible-playbook --skip-tags=molecule-notest,notest --inventory=/tmp/molecule/test/libvirt/inventory --diff /usr/lib/python2.7/site-packages/molecule/provisioner/ansible/playbooks/vagrant/destroy.yml -vvv

    ansible-playbook 2.7.8
      config file = /tmp/molecule/test/libvirt/ansible.cfg
      configured module search path = [u'/usr/lib/python2.7/site-packages/molecule/provisioner/ansible/plugins/libraries', u'/tmp/molecule/test/libvirt/library', u'/builds/test/library']
      ansible python module location = /usr/lib/python2.7/site-packages/ansible
      executable location = /usr/bin/ansible-playbook
      python version = 2.7.5 (default, Oct 30 2018, 23:45:53) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]
    Using /tmp/molecule/test/libvirt/ansible.cfg as config file
    /tmp/molecule/test/libvirt/inventory/ansible_inventory.yml did not meet host_list requirements, check plugin documentation if this is unexpected
    /tmp/molecule/test/libvirt/inventory/ansible_inventory.yml did not meet script requirements, check plugin documentation if this is unexpected
    Parsed /tmp/molecule/test/libvirt/inventory/ansible_inventory.yml inventory source with yaml plugin
    
    PLAYBOOK: destroy.yml **********************************************************
    1 plays in /usr/lib/python2.7/site-packages/molecule/provisioner/ansible/playbooks/vagrant/destroy.yml
    
    PLAY [Destroy] *****************************************************************
    META: ran handlers
    
    TASK [Destroy molecule instance(s)] ********************************************
    task path: /usr/lib/python2.7/site-packages/molecule/provisioner/ansible/playbooks/vagrant/destroy.yml:8
    <127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: root
    <127.0.0.1> EXEC /bin/sh -c 'echo ~root && sleep 0'
    <127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp/ansible-tmp-1553623562.54-225017131784001 `" && echo ansible-tmp-1553623562.54-225017131784001="` echo /root/.ansible/tmp/ansible-tmp-1553623562.54-225017131784001 `" ) && sleep 0'
    Using module file /usr/lib/python2.7/site-packages/molecule/provisioner/ansible/plugins/libraries/molecule_vagrant.py
    <127.0.0.1> PUT /root/.ansible/tmp/ansible-local-44jJJ7qy/tmpgF64pk TO /root/.ansible/tmp/ansible-tmp-1553623562.54-225017131784001/AnsiballZ_molecule_vagrant.py
    <127.0.0.1> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1553623562.54-225017131784001/ /root/.ansible/tmp/ansible-tmp-1553623562.54-225017131784001/AnsiballZ_molecule_vagrant.py && sleep 0'
    <127.0.0.1> EXEC /bin/sh -c '/usr/bin/python2 /root/.ansible/tmp/ansible-tmp-1553623562.54-225017131784001/AnsiballZ_molecule_vagrant.py && sleep 0'
    <127.0.0.1> EXEC /bin/sh -c 'rm -f -r /root/.ansible/tmp/ansible-tmp-1553623562.54-225017131784001/ > /dev/null 2>&1 && sleep 0'
    failed: [localhost] (item={'box': u'centos/7', 'provider_options': {'memory': 1024, 'cpus': 1, 'uri': u"'qemu:///system'"}, 'name': u'test-centos7', 'groups': [u'centos']}) => {
        "changed": false, 
        "item": {
            "box": "centos/7", 
            "groups": [
                "centos"
            ], 
            "name": "test-centos7", 
            "provider_options": {
                "cpus": 1, 
                "memory": 1024, 
                "uri": "'qemu:///system'"
            }
        }, 
        "module_stderr": "", 
        "module_stdout": "--> \u001b[36mValidating schema /builds/test/molecule/libvirt/molecule.yml.\u001b[0m\n\u001b[0m\u001b[32mValidation completed successfully.\u001b[0m\n\u001b[0m\n{\"invocation\": {\"module_args\": {\"config_options\": {}, \"platform_box_url\": null, \"provider_cpus\": 2, \"provider_raw_config_args\": null, \"platform_box\": \"centos/7\", \"provider_override_args\": null, \"state\": \"destroy\", \"instance_interfaces\": [], \"instance_name\": \"test-centos7\", \"platform_box_version\": null, \"provider_memory\": 512, \"instance_raw_config_args\": null, \"provider_options\": {\"memory\": 1024, \"uri\": \"'qemu:///system'\", \"cpus\": 1}, \"provider_name\": \"libvirt\", \"provision\": false, \"force_stop\": true}}, \"changed\": false}\u001b[0m\n\u001b[0m", 
        "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", 
        "rc": 0
    }
    
    PLAY RECAP *********************************************************************
    localhost                  : ok=0    changed=0    unreachable=0    failed=1

**Comment by WojciechPolnik** [comment] 2019-03-26 18:16
I would like to add that lint and syntax works without any problems

**Comment by decentral1se** [comment] 2019-03-26 18:24
> "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error"

Where is that failure message? I still can't see it?

**Comment by WojciechPolnik** [comment] 2019-03-26 18:27
Em. because it literally shows no message.
<img width="882" alt="Screenshot 2019-03-26 at 19 27 01" src="https://user-images.githubusercontent.com/26327820/55023489-31a92680-4ffd-11e9-81f4-34f3e5702d33.png">

**Comment by WojciechPolnik** [comment] 2019-03-26 18:33
I've tested docker driver and there is no issue too. Then now its only left to Vagrant/Libvirt

**Comment by vin01** [comment] 2019-03-29 09:43
**Molecule version:** 2.20.0

I ran into the same issue with Jenkins. With PY_COLORS=1, same error would occur as provided in the screenshot in above comment.

However, it does not seem to have anything to do with `sudo` but because of [colorama's autoreset](https://github.com/ansible/molecule/blob/master/molecule/logger.py#L37). 

This is the [line of code](https://github.com/ansible/molecule/blob/master/molecule/logger.py#L37) which causes the issue:

```
colorama.init(autoreset=True, strip=not should_do_markup())
```

I was able to get it to work successfully by setting autoreset according to the value of PY_COLORS. So, following works:

```
color_setting=not should_do_markup()
colorama.init(autoreset=color_setting, strip=color_setting)
```

Since PY_COLORS is mainly useful for CI systems with non-interactive shells, I think autoreset shall also be set accordingly. I was able to find [this related issue](https://github.com/tartley/colorama/issues/47) in colorama which suggests that autoreset does not work as expected when there is no tty.

**Reproduction steps**

1. `export `PY_COLORS=1` (tested only in bash)
2. `molecule --debug destroy`

Please review if my assessment is correct or if a better approach is possible? I will be happy to send a PR for the same.

**Comment by ssbarnea** [comment] 2019-03-29 11:15
This is weird, especially after reading https://pypi.org/project/colorama/ docs on auto-reset. 

So far I did not encounter the bug myself but based on the documentation I would not mind if we set autoreset to False *when* strip=True because if we do not do ANSI, it makes no sense to send reset sequences either. On the other hand, if strip=False, autoreset may be desired in order to avoid one output line to set the color forever.

**Comment by vin01** [comment] 2019-03-29 12:33
This is what I get with those variables also set in the env alongwith PY_COLORS=1.

```
    TASK [Destroy molecule instance(s)] ********************************************
    task path: /home/USER/.local/lib/python2.7/site-packages/molecule/provisioner/ansible/playbooks/vagrant/destroy.yml:8
    Using module file /home/USER/.local/lib/python2.7/site-packages/molecule/provisioner/ansible/plugins/libraries/molecule_vagrant.py
    <127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: USER
    <127.0.0.1> EXEC /bin/sh -c '/usr/bin/python && sleep 0'
    failed: [localhost] (item={'box': u'ubuntu/bionic64', 'memory': 2048, 'cpus': 2, 'name': u'ubuntu-18.04-bionic64'}) => {
        "changed": false, 
        "item": {
            "box": "ubuntu/bionic64", 
            "cpus": 2, 
            "memory": 2048, 
            "name": "ubuntu-18.04-bionic64"
        }, 
        "rc": 0
    }
    
    MSG:
    
    MODULE FAILURE
    See stdout/stderr for the exact error
    
    
    MODULE_STDOUT:
    
    --> Validating schema /home/USER/s/molecule/default/molecule.yml.
    Validation completed successfully.
    
    {"invocation": {"module_args": {"config_options": {}, "platform_box_url": null, "provider_cpus": 2, "provider_raw_config_args": null, "platform_box": "ubuntu/bionic64", "provider_override_args": null, "state": "destroy", "instance_interfaces": [], "instance_name": "ubuntu-18.04-bionic64", "platform_box_version": null, "provider_memory": 512, "instance_raw_config_args": null, "provider_options": {}, "provider_name": "virtualbox", "provision": false, "force_stop": true}}, "changed": false}
    
    
    
    PLAY RECAP *********************************************************************
    localhost                  : ok=0    changed=0    unreachable=0    failed=1   
    
    
ERROR: 
```

values of other env vars which might be relevant:

```
TERM=xterm-256color
```

**Comment by cyberxml** [comment] 2019-04-23 14:17
I am experiencing very similar appearing issue on CentOS 7. Same ansible/molecule/vagrant files run without issue on Fedora 29, but fail as unprivileged user on C7. Run molecule via sudo on C7, and the create/destroy tasks work without issue. The one-liner patch to logger.py suggested above, does not fix this issue for unpriv user on C7.

**Comment by decentral1se** [comment] 2019-04-23 15:15
FYI, https://github.com/ansible/molecule/pull/2001 was merged which was chasing some bug related to the colorama code which is also related here. Perhaps give a re-run with the latest master and see if that is working.

**Comment by WojciechPolnik** [comment] 2019-04-23 15:33
god bless 
works for me 💯 ❤️

**Comment by decentral1se** [comment] 2019-04-23 15:54
cc @jctanner @ssbarnea - any chance to follow up on `PY_COLORS` not being respected?

**Comment by WojciechPolnik** [comment] 2019-08-01 12:21
```
pip install   --index-url https://test.pypi.org/simple   --extra-index-url https://pypi.org/simple   molecule==2.22rc4.dev10
```
give the same issue

**Comment by ssbarnea** [comment] 2020-01-14 12:22
Molecule Vagrant driver was moved to https://github.com/pycontribs/molecule-vagrant/issues and if this issue is still valid, please raise a ticket there. Thanks.

**Closed by ssbarnea** 2020-01-14 12:22 UTC
Labels: bug, vagrant

**Comment by emcniece** [comment] 2020-08-10 20:12
https://github.com/ansible-community/molecule/pull/2001 seems to have caused a regression - I can only get Colorama to properly apply `strip=True` when the init call is in `logger.py`. When the init call is elsewhere (as of v2.22 it's in `shell.py`) the charcode stripping doesn't take effect.

Is this an init race condition? Looks like it with some quick logging:

```py
# shell.py
click_completion.init()
print('shell init')
colorama.init(autoreset=True, strip=not should_do_markup())
print('shell init - colorama done')
...
```

```py
# logger.py
from ansible.module_utils.parsing.convert_bool import boolean as to_bool
print('logger init')
def should_do_markup():
  ...
```

```sh
$ PY_COLORS=0 molecule test -s myscenario
logger init
shell init
shell init - colorama done
```

This can be resolved by moving `colorama.init()` up above any `from molecule.logger` imports, but this fails with the current architecture because `colorama.init()` relies on `from molecule.logger import should_do_markup`.

Proposal: move `should_do_markup` to `util.py` as it is a functional method and has no package-local dependencies. Does this sound sane?
