### ISSUE TITLE
Unable to build Dockerfile

### ISSUE THREAD

**Issue by glcx** [ansible/molecule#1725] opened 2019-02-05 13:37 UTC
# Issue Type

- Bug report

Unable to build Molecule Dockerfile

# Desired Behavior

Build the Docker Image, install the python packages list with pip

> ENV PACKAGES="\
>     gcc \
>     make \
>     bash \
>     shadow \
>     libffi-dev \
>     musl-dev \
>     openssl-dev \
>     py-pip \
>     python \
>     python-dev \
>     linux-headers \
>     sudo \
>     rsync \
>     curl \
>     ruby \
>     ruby-dev \
>     ruby-etc \
>     ruby-rdoc \
>     ruby-irb \
>     git \
> "

# Actual Behaviour

Fails in pip install stage `pip install --no-cache-dir ${PIP_PACKAGES}`

> Exception:
> Traceback (most recent call last):
>   File "/usr/lib/python2.7/site-packages/pip/_internal/cli/base_command.py", line 176, in main
>     status = self.run(options, args)
>   File "/usr/lib/python2.7/site-packages/pip/_internal/commands/install.py", line 346, in run
>     session=session, autobuilding=True
>   File "/usr/lib/python2.7/site-packages/pip/_internal/wheel.py", line 886, in build
>     assert have_directory_for_build
> AssertionError
> The command '/bin/sh -c apk update     && apk add --update --no-cache ${PACKAGES}     && rm -rf /var/cache/apk/*     && pip install --upgrade pip     && pip install --no-cache-dir ${PIP_PACKAGES}     && rm -rf /root/.cache     && gem install ${GEM_PACKAGES}     && adduser -D -h ${TEST_HOME_DIR} ${TEST_USER}     && usermod -aG dockremap ${TEST_USER}     && echo "${TEST_USER} ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers' returned a non-zero code: 2

**Comment by glcx** [comment] 2019-02-06 09:31
Potentially related to: https://github.com/pypa/pip/issues/6197

**Comment by lwm** [comment] 2019-02-06 10:20
@glcx, any ideas on a fix? Thanks for the solid detective work.

**Comment by glcx** [comment] 2019-02-06 10:49
@lwm One of the fix would be to use  `&& pip install --no-cache-dir **--no-use-pep517** -r ${PIP_PACKAGES} \`

A new version of pip will be released with the fix. (Anytime soon) so it's probably not needed unless we have a new molecule release coming.

**Comment by lwm** [comment] 2019-02-06 20:05
So, right, we have a fix incoming via https://github.com/pypa/pip/issues/6197#issuecomment-459947065.

**Comment by themr0c** [comment] 2019-02-06 20:26
Did you try to build from the master branch ? 
In that branch the Dockerfile is referencing ENV PIP_PACKAGES="molecule[azure,docker,docs,ec2,gce,lxc,openstack,vagrant,windows]     virtualenv "
But the new pip package has not been released yet, and it is necessary because it will include all the extras ([azure,docker,docs,ec2,gce,lxc,openstack,vagrant,windows]) that are not present in the 2.19 pip package.

**Comment by themr0c** [comment] 2019-02-06 20:29
Actually, you should have these errors in the logs, previous to the python failure:
```
  molecule 2.19.0 does not provide the extra 'azure'
  molecule 2.19.0 does not provide the extra 'docker'
  molecule 2.19.0 does not provide the extra 'docs'
  molecule 2.19.0 does not provide the extra 'ec2'
  molecule 2.19.0 does not provide the extra 'gce'
  molecule 2.19.0 does not provide the extra 'lxc'
  molecule 2.19.0 does not provide the extra 'openstack'
  molecule 2.19.0 does not provide the extra 'vagrant'
  molecule 2.19.0 does not provide the extra 'windows'
```

**Comment by ssbarnea** [comment] 2019-02-06 20:45
True this is caused by the fact that documentation is on master and not on last release. Things like calling as python module and extras are not working with last release but they work with master. Another reason to release more often.

**Comment by lwm** [comment] 2019-02-07 11:18
OK, great, thanks for clearing up. Let's keep this open to track until we make the next release.

**Comment by glcx** [comment] 2019-02-11 09:58
19.0.2 released. Original issue is now fixed.

**Comment by lwm** [comment] 2019-02-13 01:04
Thank you @glcx!

**Comment by gundalow** [comment] 2019-02-13 09:01
Original issue is fixed, so closing. 
If there are other problems please raise individual issues for those.

**Closed by gundalow** 2019-02-13 09:01 UTC
Labels: bug
