### ISSUE TITLE
migrate from travis to shippable (ansible current ci)

### ISSUE THREAD

**Issue by ssbarnea** [ansible/molecule#1874] opened 2019-03-23 11:13 UTC
We should try to switch over from Travist o Shippable because travis performance become unresonable slow with average time for a build to WAIT in queue going over 6-8 hours.

Migrating to Ansible own CI system first makes sense and converting the travis configuration into shippable one should be a very easy task.

Please use +1/-1 or comments to address support for this.

**Comment by webknjaz** [comment] 2019-03-23 17:48
I think @mattclay wouldn't have resources to support yet another repo...

Also, it's a duplicate of #1770. All discussions should go there.

**Comment by decentral1se** [comment] 2019-03-23 19:54
But what about the Zuul CI plan? That was a really good direction, I though ...

**Comment by webknjaz** [comment] 2019-03-23 22:52
I think Zuul looks like a way to go now. I'm not sure why Sorin brought up Shippable. Also, the point is unclear: the problem is with having an unpaid version, you cannot compare it with a paid version of another service. If we were to pay Travis, there would be no queueing problem which rounds things up.
With free shippable, it'd be even worse since it has just one simultaneous job.

**Comment by gundalow** [comment] 2019-03-25 18:42
Closing this and moving to https://github.com/ansible/molecule/issues/1874

**Closed by gundalow** 2019-03-25 18:42 UTC
Labels: enhancement

**Comment by webknjaz** [comment] 2019-03-25 18:48
s/#1874/#1770/
