### ISSUE TITLE
Error: no such object

### ISSUE THREAD

**Issue by ivansche** [ansible/molecule#1824] opened 2019-03-12 11:18 UTC
# Issue Type

- Bug report

# Molecule and Ansible details

```
ansible --2.7.5 && molecule --2.19.0
```

Molecule installation method (one of):

- pip

Ansible installation method (one of):

- pip

Detail any linters or test runners used:

# Desired Behavior

I want molecule to create a docker image from a dockerfile to be used for test. 

My dockerfile is:
 
     FROM ubuntu:16.04

     ENV pip_packages "ansible pyopenssl yamllint ansible-lint flake8 testinfra molecule"

     \# Install dependencies.
     RUN apt-get update \
         && apt-get install -y --no-install-recommends \
            build-essential \
            python-software-properties \
            software-properties-common \
            python-setuptools \
            python-dev \
            python-pip \
            rsyslog systemd systemd-cron sudo \
         && rm -Rf /var/lib/apt/lists/* \
         && rm -Rf /usr/share/doc && rm -Rf /usr/share/man \
         && apt-get clean
     RUN sed -i 's/^\($ModLoad imklog\)/#\1/' /etc/rsyslog.conf

     \# Install Ansible via Pip.
     RUN pip install $pip_packages

     COPY initctl_faker .
     RUN chmod +x initctl_faker && rm -fr /sbin/initctl && ln -s /initctl_faker /sbin/initctl

     \# Install Ansible inventory file.
     RUN mkdir -p /etc/ansible
     RUN echo "[local]\nlocalhost ansible_connection=local" > /etc/ansible/hosts

     EXPOSE 5432

     VOLUME ["/sys/fs/cgroup", "/tmp", "/run"]
     CMD ["/lib/systemd/systemd"]`

My molecule.yml file is: 

     dependency:
       name: galaxy
     driver:
       name: docker
     lint:
       name: yamllint
     platforms:
       - name: docker-ubuntu
         image: ubuntu
         image-version: "16.04"
         privileged: true
         pull: true
         pid_mode: host
         dockerfile: molecule/default/Dockerfile.js
         exposed_port:
             - "5432"
         pre_build_image: false
         command: ""
         volumes:
           - /sys/fs/cgroup:/sys/fs/cgroup:ro
     ...

# Actual Behaviour

molecule --debug converge gives:

     -> Scenario: 'default'
     --> Scenario: 'default'
     --> Action: 'converge'
     DEBUG: ANSIBLE ENVIRONMENT
     stgresql/default/plugins/filters:/home/ivan/workspace/ansible-role-postgresql/plugins/filters
     ANSIBLE_LIBRARY: /usr/local/lib/python3.6/dist-packages/molecule/provisioner/ansible/plugins/libraries:/tmp/molecule/ansible-role-postgreDEBUG: MOLECULE ENVIRONMENT
     ---
     MOLECULE_DEBUG: 'True'
     MOLECULE_DEPENDENCY_NAME: galaxy
     MOLECULE_DRIVER_NAME: docker
     MOLECULE_ENV_FILE: /home/ivan/workspace/ansible-role-postgresql/.env.yml
     MOLECULE_EPHEMERAL_DIRECTORY: /tmp/molecule/ansible-role-postgresql/default
     MOLECULE_FILE: /home/ivan/workspace/ansible-role-postgresql/molecule/default/molecule.yml
     MOLECULE_INSTANCE_CONFIG: /tmp/molecule/ansible-role-postgresql/default/instance_config.yml
     MOLECULE_INVENTORY_FILE: /tmp/molecule/ansible-role-postgresql/default/ansible_inventory.yml
     MOLECULE_LINT_NAME: yamllint
     MOLECULE_PROJECT_DIRECTORY: /home/ivan/workspace/ansible-role-postgresql
     MOLECULE_PROVISIONER_LINT_NAME: ansible-lint
     MOLECULE_PROVISIONER_NAME: ansible
     MOLECULE_SCENARIO_DIRECTORY: /home/ivan/workspace/ansible-role-postgresql/molecule/default
     MOLECULE_SCENARIO_NAME: default
     MOLECULE_VERIFIER_LINT_NAME: flake8
     MOLECULE_VERIFIER_NAME: testinfra
     MOLECULE_VERIFIER_TEST_DIRECTORY: /home/ivan/workspace/ansible-role-postgresql/molecule/default/tests

     DEBUG: SHELL REPLAY
     ANSIBLE_CONFIG=/tmp/molecule/ansible-role-postgresql/default/ansible.cfg      
     ANSIBLE_FILTER_PLUGINS=/usr/local/lib/python3.6/dist-packages/molecule/provisioner/ansible/plugins/filters:/tmp/molecule/ansible-role-postgresql/default/plugins/filters:/home/ivan/workspace/ansible-role-postgresql/plugins/filters ANSIBLE_LIBRARY=/usr/local/lib/python3.6/dist-packages/molecule/provisioner/ansible/plugins/libraries:/tmp/molecule/ansible-role-postgresql/default/library:/home/ivan/workspace/ansible-role-postgresql/library ANSIBLE_ROLES_PATH=/tmp/molecule/ansible-role-postgresql/default/roles:/home/ivan/workspace MOLECULE_DEBUG=True 
     MOLECULE_DEPENDENCY_NAME=galaxy MOLECULE_DRIVER_NAME=docker 
     MOLECULE_ENV_FILE=/home/ivan/workspace/ansible-role-postgresql/.env.yml 
     MOLECULE_EPHEMERAL_DIRECTORY=/tmp/molecule/ansible-role-postgresql/default       
     MOLECULE_FILE=/home/ivan/workspace/ansible-role-postgresql/molecule/default/molecule.yml 
     MOLECULE_INSTANCE_CONFIG=/tmp/molecule/ansible-role-postgresql/default/instance_config.yml 
     MOLECULE_INVENTORY_FILE=/tmp/molecule/ansible-role-postgresql/default/ansible_inventory.yml 
     MOLECULE_LINT_NAME=yamllint MOLECULE_PROJECT_DIRECTORY=/home/ivan/workspace/ansible-role-postgresql MOLECULE_PROVISIONER_LINT_NAME=ansible-lint 
     MOLECULE_PROVISIONER_NAME=ansible MOLECULE_SCENARIO_DIRECTORY=/home/ivan/workspace/ansible-role-postgresql/molecule/default MOLECULE_SCENARIO_NAME=default 
     MOLECULE_VERIFIER_LINT_NAME=flake8 MOLECULE_VERIFIER_NAME=testinfra 
     MOLECULE_VERIFIER_TEST_DIRECTORY=/home/ivan/workspace/ansible-role-postgresql/molecule/default/tests

     DEBUG: COMMAND
     /usr/local/bin/ansible-playbook --skip-tags=molecule-notest,notest --diff --inventory=/tmp/molecule/ansible-role-postgresql/default/ansible_inventory.yml /home/ivan/workspace/ansible-role-postgresql/molecule/default/playbook.yml -vvv

    ansible-playbook 2.7.5
      config file = /tmp/molecule/ansible-role-postgresql/default/ansible.cfg
      configured module search path = ['/usr/local/lib/python3.6/dist-packages/molecule/provisioner/ansible/plugins/libraries', '/tmp/molecule/ansible-role-postgresql/default/library', '/home/ivan/workspace/ansible-role-postgresql/library']
      ansible python module location = /usr/local/lib/python3.6/dist-packages/ansible
      executable location = /usr/local/bin/ansible-playbook
      python version = 3.6.7 (default, Oct 22 2018, 11:32:17) [GCC 8.2.0]
    Using /tmp/molecule/ansible-role-postgresql/default/ansible.cfg as config file
    /tmp/molecule/ansible-role-postgresql/default/ansible_inventory.yml did not meet host_list requirements, check plugin documentation if this is unexpected
    /tmp/molecule/ansible-role-postgresql/default/ansible_inventory.yml did not meet script requirements, check plugin documentation if this is unexpected
    Parsed /tmp/molecule/ansible-role-postgresql/default/ansible_inventory.yml inventory source with yaml plugin
    
    PLAYBOOK: playbook.yml *********************************************************
    1 plays in /home/ivan/workspace/ansible-role-postgresql/molecule/default/playbook.yml
    
    PLAY [Converge] ****************************************************************
    
    TASK [Gathering Facts] *********************************************************
    task path: /home/ivan/workspace/ansible-role-postgresql/molecule/default/playbook.yml:2
    [WARNING]: unable to retrieve default user from docker container:   Error: No
    such object: docker-ubuntu

    <docker-ubuntu> ESTABLISH DOCKER CONNECTION FOR USER: ?
    <docker-ubuntu> EXEC ['/usr/bin/docker', b'exec', b'-i', 'docker-ubuntu', '/bin/sh', '-c', "/bin/sh -c 'echo ~ && sleep 0'"]
    <docker-ubuntu> EXEC ['/usr/bin/docker', b'exec', b'-i', 'docker-ubuntu', '/bin/sh', '-c', '/bin/sh -c \'echo "`pwd`" && sleep 0\'']
    <docker-ubuntu> EXEC ['/usr/bin/docker', b'exec', b'-i', 'docker-ubuntu', '/bin/sh', '-c', '/bin/sh -c \'( umask 77 && mkdir -p "` echo ~/.ansible/tmp/ansible-tmp-1552389445.407965-269972299601421 `" && echo ansible-tmp-1552389445.407965-269972299601421="` echo ~/.ansible/tmp/ansible-tmp-1552389445.407965-269972299601421 `" ) && sleep 0\'']
    fatal: [docker-ubuntu]: UNREACHABLE! => {
        "changed": false,
        "msg": "Authentication or permission failure. In some cases, you may have been able to authenticate and did not have permissions on the target directory. Consider changing the remote tmp path in ansible.cfg to a path rooted in \"/tmp\". Failed command was: ( umask 77 && mkdir -p \"` echo ~/.ansible/tmp/ansible-tmp-1552389445.407965-269972299601421 `\" && echo ansible-tmp-1552389445.407965-269972299601421=\"` echo ~/.ansible/tmp/ansible-tmp-1552389445.407965-269972299601421 `\" ), exited with result 1",
        "unreachable": true
    }
    
    PLAY RECAP *********************************************************************
    docker-ubuntu              : ok=0    changed=0    unreachable=1    failed=0
    
    
     ERROR:`

**Comment by decentral1se** [comment] 2019-03-12 13:32
Hi @ivansche, it seems the relevant part is:

> unable to retrieve default user from docker container:   Error: No such object: docker-ubuntu

You ran `molecule converge` before you ran `molecule create`?

btw, I am unclear why you are installing Molecule and friends test dependencies into a container which you will test a role against? But anyway, that is beyond the point of addressing this issue.

**Comment by ivansche** [comment] 2019-03-12 14:15
So when I do `molecule create` I get:

     --> Validating schema /home/ivan/workspace/ansible-role-postgresql/molecule/default/molecule.yml.
     Validation completed successfully.
     --> Test matrix
    
     └── default
         ├── create
         └── prepare
    
     --> Scenario: 'default'
     --> Action: 'create'
     Skipping, instances already created.
     --> Scenario: 'default'
     --> Action: 'prepare'
     Skipping, prepare playbook not configured.

after I do `docker ps -a` the latest image was created a few weeks ago, even though `molecule create` was run minutes earlier

**Comment by decentral1se** [comment] 2019-03-12 14:25
Hmmmm, `dockerfile: molecule/default/Dockerfile.js`? I don't think you can override that in v2.19 and is it the case that your Dockerfile is not named `Dockerfile.j2`? Maybe it is failing to pick that up somehow ...

**Comment by webknjaz** [comment] 2019-03-12 14:44
@ivansche did you intend to have a `*.js` extension or maybe it's a typo for `*.j2`?

**Comment by ivansche** [comment] 2019-03-12 14:55
I thought of that too, but changing it to .j2 did not do anything with the error.

**Comment by ivansche** [comment] 2019-03-12 14:59
Also this is my playbook.yml in default scenario: 

     ---
     - name: Converge
       hosts: all
       roles:
         - role: ansible-role-postgresql

Maybe that might help.

**Comment by ivansche** [comment] 2019-03-12 15:05
This is my `playbook.yml`:
     
     ---
     - name: Converge
       hosts: all
       roles:
         - role: ansible-role-postgresql

Maybe that will help.

**Comment by gofrolist** [comment] 2019-05-03 17:05
Had the same issue.
Fixed by run `molecule destroy` command first

**Comment by evadeflow** [comment] 2019-10-27 13:09
> Had the same issue.
> Fixed by run `molecule destroy` command first

Yes—thank you, @gofrolist! I had the exact same problem, and `molecule destroy` cleared it up.

**Comment by decentral1se** [comment] 2019-10-27 13:11
Optimistically closing this one off then folks :+1:

**Closed by decentral1se** 2019-10-27 13:11 UTC
Labels: bug

**Comment by coaxial** [comment] 2020-11-29 13:34
It happened to me as well. I did try to use an alternative user by adding this to molecule.yml:

```yaml
provisioner:
   name: ansible
   inventory:
     host_vars:
       ubuntu2004:
         ansible_user: ansible
```

but I hadn't run `molecule destroy`. I ran `molecule destroy` afterwards, I have nothing running according to `docker ps -a`, but it doesn't matter: molecule refuses to prepare anything and fails with this error, whether I comment out the `inventory: ` section in `molecule.yml` or not.


`molecule --debug create`:
```
--> Test matrix

└── default
    └── prepare

--> Scenario: 'default'
--> Action: 'prepare'
--> Sanity checks: 'docker'
DEBUG: ANSIBLE ENVIRONMENT
---
ANSIBLE_COLLECTIONS_PATH: /home/coaxial/.cache/molecule/ansible-playbook/default/collections:/home/coaxial/.ansible/collections:/usr/share/ansible/collections:/etc/ansible/collections
ANSIBLE_CONFIG: /home/coaxial/.cache/molecule/ansible-playbook/default/ansible.cfg
ANSIBLE_FILTER_PLUGINS: /home/coaxial/.virtualenvs/ansible/lib/python3.8/site-packages/molecule/provisioner/ansible/plugins/filter:/home/coaxial/.cache/molecule/ansible-playbook/default/plugins/filter:/home/coaxial/dotfiles/ansible-playbook/plugins/filter:/home/coaxial/.ansible/plugins/filter:/usr/share/ansible/plugins/filter
ANSIBLE_LIBRARY: /home/coaxial/.virtualenvs/ansible/lib/python3.8/site-packages/molecule/provisioner/ansible/plugins/modules:/home/coaxial/.cache/molecule/ansible-playbook/default/library:/home/coaxial/dotfiles/ansible-playbook/library:/home/coaxial/.ansible/plugins/modules:/usr/share/ansible/plugins/modules
ANSIBLE_ROLES_PATH: /home/coaxial/.cache/molecule/ansible-playbook/default/roles:/home/coaxial/dotfiles:/home/coaxial/.ansible/roles:/usr/share/ansible/roles:/etc/ansible/roles

DEBUG: MOLECULE ENVIRONMENT
---
MOLECULE_DEBUG: 'True'
MOLECULE_DEPENDENCY_NAME: galaxy
MOLECULE_DRIVER_NAME: docker
MOLECULE_ENV_FILE: /home/coaxial/dotfiles/ansible-playbook/.env.yml
MOLECULE_EPHEMERAL_DIRECTORY: /home/coaxial/.cache/molecule/ansible-playbook/default
MOLECULE_FILE: /home/coaxial/.cache/molecule/ansible-playbook/default/molecule.yml
MOLECULE_INSTANCE_CONFIG: /home/coaxial/.cache/molecule/ansible-playbook/default/instance_config.yml
MOLECULE_INVENTORY_FILE: /home/coaxial/.cache/molecule/ansible-playbook/default/inventory/ansible_inventory.yml
MOLECULE_PROJECT_DIRECTORY: /home/coaxial/dotfiles/ansible-playbook
MOLECULE_PROVISIONER_NAME: ansible
MOLECULE_SCENARIO_DIRECTORY: /home/coaxial/dotfiles/ansible-playbook/molecule/default
MOLECULE_SCENARIO_NAME: default
MOLECULE_STATE_FILE: /home/coaxial/.cache/molecule/ansible-playbook/default/state.yml
MOLECULE_VERIFIER_NAME: testinfra
MOLECULE_VERIFIER_TEST_DIRECTORY: /home/coaxial/dotfiles/ansible-playbook/molecule/default/tests

DEBUG: SHELL REPLAY
ANSIBLE_COLLECTIONS_PATH=/home/coaxial/.cache/molecule/ansible-playbook/default/collections:/home/coaxial/.ansible/collections:/usr/share/ansible/collections:/etc/ansible/collections ANSIBLE_CONFIG=/home/coaxial/.cache/molecule/ansible-playbook/default/ansible.cfg ANSIBLE_FILTER_PLUGINS=/home/coaxial/.virtualenvs/ansible/lib/python3.8/site-packages/molecule/provisioner/ansible/plugins/filter:/home/coaxial/.cache/molecule/ansible-playbook/default/plugins/filter:/home/coaxial/dotfiles/ansible-playbook/plugins/filter:/home/coaxial/.ansible/plugins/filter:/usr/share/ansible/plugins/filter ANSIBLE_LIBRARY=/home/coaxial/.virtualenvs/ansible/lib/python3.8/site-packages/molecule/provisioner/ansible/plugins/modules:/home/coaxial/.cache/molecule/ansible-playbook/default/library:/home/coaxial/dotfiles/ansible-playbook/library:/home/coaxial/.ansible/plugins/modules:/usr/share/ansible/plugins/modules ANSIBLE_ROLES_PATH=/home/coaxial/.cache/molecule/ansible-playbook/default/roles:/home/coaxial/dotfiles:/home/coaxial/.ansible/roles:/usr/share/ansible/roles:/etc/ansible/roles MOLECULE_DEBUG=True MOLECULE_DEPENDENCY_NAME=galaxy MOLECULE_DRIVER_NAME=docker MOLECULE_ENV_FILE=/home/coaxial/dotfiles/ansible-playbook/.env.yml MOLECULE_EPHEMERAL_DIRECTORY=/home/coaxial/.cache/molecule/ansible-playbook/default MOLECULE_FILE=/home/coaxial/.cache/molecule/ansible-playbook/default/molecule.yml MOLECULE_INSTANCE_CONFIG=/home/coaxial/.cache/molecule/ansible-playbook/default/instance_config.yml MOLECULE_INVENTORY_FILE=/home/coaxial/.cache/molecule/ansible-playbook/default/inventory/ansible_inventory.yml MOLECULE_PROJECT_DIRECTORY=/home/coaxial/dotfiles/ansible-playbook MOLECULE_PROVISIONER_NAME=ansible MOLECULE_SCENARIO_DIRECTORY=/home/coaxial/dotfiles/ansible-playbook/molecule/default MOLECULE_SCENARIO_NAME=default MOLECULE_STATE_FILE=/home/coaxial/.cache/molecule/ansible-playbook/default/state.yml MOLECULE_VERIFIER_NAME=testinfra MOLECULE_VERIFIER_TEST_DIRECTORY=/home/coaxial/dotfiles/ansible-playbook/molecule/default/tests

DEBUG: COMMAND
/home/coaxial/.virtualenvs/ansible/bin/ansible-playbook --skip-tags=molecule-notest,notest --diff --inventory=/home/coaxial/.cache/molecule/ansible-playbook/default/inventory /home/coaxial/dotfiles/ansible-playbook/molecule/default/prepare.yml -vvv

    ansible-playbook 2.10.3
      config file = /home/coaxial/.cache/molecule/ansible-playbook/default/ansible.cfg
      configured module search path = ['/home/coaxial/.virtualenvs/ansible/lib/python3.8/site-packages/molecule/provisioner/ansible/plugins/modules', '/home/coaxial/.cache/molecule/ansible-playbook/default/library', '/home/coaxial/dotfiles/ansible-playbook/library', '/home/coaxial/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
      ansible python module location = /home/coaxial/.virtualenvs/ansible/lib/python3.8/site-packages/ansible
      executable location = /home/coaxial/.virtualenvs/ansible/bin/ansible-playbook
      python version = 3.8.5 (default, Jul 28 2020, 12:59:40) [GCC 9.3.0]
    Using /home/coaxial/.cache/molecule/ansible-playbook/default/ansible.cfg as config file
    host_list declined parsing /home/coaxial/.cache/molecule/ansible-playbook/default/inventory/ansible_inventory.yml as it did not pass its verify_file() method
    script declined parsing /home/coaxial/.cache/molecule/ansible-playbook/default/inventory/ansible_inventory.yml as it did not pass its verify_file() method
    Parsed /home/coaxial/.cache/molecule/ansible-playbook/default/inventory/ansible_inventory.yml inventory source with yaml plugin
    redirecting (type: modules) ansible.builtin.archive to community.general.archive
    Skipping callback 'default', as we already have a stdout callback.
    Skipping callback 'minimal', as we already have a stdout callback.
    Skipping callback 'oneline', as we already have a stdout callback.

    PLAYBOOK: prepare.yml **********************************************************
    1 plays in /home/coaxial/dotfiles/ansible-playbook/molecule/default/prepare.yml

    PLAY [Prepare] *****************************************************************

    TASK [Gathering Facts] *********************************************************
    task path: /home/coaxial/dotfiles/ansible-playbook/molecule/default/prepare.yml:2
    redirecting (type: connection) ansible.builtin.docker to community.general.docker
[WARNING]: unable to retrieve default user from docker container:   Error: No
such object: ubuntu2004
    <ubuntu2004> ESTABLISH DOCKER CONNECTION FOR USER: ?
    <ubuntu2004> EXEC ['/usr/bin/docker', b'exec', b'-i', 'ubuntu2004', '/bin/sh', '-c', "/bin/sh -c 'echo ~ && sleep 0'"]
    <ubuntu2004> EXEC ['/usr/bin/docker', b'exec', b'-i', 'ubuntu2004', '/bin/sh', '-c', '/bin/sh -c \'echo "`pwd`" && sleep 0\'']
    <ubuntu2004> EXEC ['/usr/bin/docker', b'exec', b'-i', 'ubuntu2004', '/bin/sh', '-c', '/bin/sh -c \'( umask 77 && mkdir -p "` echo ~/.ansible/tmp `"&& mkdir "` echo ~/.ansible/tmp/ansible-tmp-1606656467.7878945-68143-130377399527997 `" && echo ansible-tmp-1606656467.7878945-68143-130377399527997="` echo ~/.ansible/tmp/ansible-tmp-1606656467.7878945-68143-130377399527997 `" ) && sleep 0\'']
fatal: [ubuntu2004]: UNREACHABLE! => {
    "changed": false,
    "msg": "Failed to create temporary directory.In some cases, you may have been able to authenticate and did not have permissions on the target directory. Consider changing the remote tmp path in ansible.cfg to a path rooted in \"/tmp\", for more error information use -vvv. Failed command was: ( umask 77 && mkdir -p \"` echo ~/.ansible/tmp `\"&& mkdir \"` echo ~/.ansible/tmp/ansible-tmp-1606656467.7878945-68143-130377399527997 `\" && echo ansible-tmp-1606656467.7878945-68143-130377399527997=\"` echo ~/.ansible/tmp/ansible-tmp-1606656467.7878945-68143-130377399527997 `\" ), exited with result 1",
    "unreachable": true
}

    PLAY RECAP *********************************************************************
    ubuntu2004                 : ok=0    changed=0    unreachable=1    failed=0    skipped=0    rescued=0    ignored=0

ERROR:

```

**Comment by garthwilliamson** [comment] 2021-11-22 02:57
In case anyone else finds this after running into the same issue I did:

`molecule init default` by default creates a 'create.yml' that isn't compatible with docker. I suspect in a lot of cases for people who run into this issue, the problem is that the create step failed. Once it's fixed, you have to destroy before trying again.

**Comment by jdelStrother** [comment] 2024-05-14 16:36
> In case anyone else finds this after running into the same issue I did:
> 
> `molecule init default` by default creates a 'create.yml' that isn't compatible with docker. I suspect in a lot of cases for people who run into this issue, the problem is that the create step failed. Once it's fixed, you have to destroy before trying again.

In case I can save anyone else a lost afternoon, just to expand on this -
The presence of the generated molecule/create.yml will prevent the docker molecule plugin from running its own default [create.yml](https://github.com/ansible-community/molecule-plugins/blob/b48ead5d12d80eb90ead14f1958d0e9ef79b8752/src/molecule_plugins/docker/playbooks/create.yml#L59) , so it doesn't actually create a docker container before attempting the rest of the play.

I fixed it by deleting create.yml & destroy.yml, and re-running `molecule destroy && molecule create`.
