### ISSUE TITLE
Error 'Failed to connect to the host via ssh' using Molecule Vagrant Module

### ISSUE THREAD

**Issue by SergeyBear** [ansible/molecule#2077] opened 2019-05-29 09:31 UTC
# Issue Type

- Bug report

I tried to use Molecule with Molecule Vagrant Module, but I get the same error regardless of VairtualBox or Libvirt provider:
```
$ molecule create
--> Validating schema /home/user/molecule/ansible/molecule/default/molecule.yml.
Validation completed successfully.
--> Test matrix
    
└── default
    ├── create
    └── prepare
    
--> Scenario: 'default'
--> Action: 'create'
Skipping, instances already created.
--> Scenario: 'default'
--> Action: 'prepare'
    
    PLAY [Prepare] *****************************************************************
    
    TASK [Install python for Ansible] **********************************************
    fatal: [centos7]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh: ssh: Could not resolve hostname centos7: Name or service not known", "unreachable": true}
    
    PLAY RECAP *********************************************************************
    centos7                    : ok=0    changed=0    unreachable=1    failed=0    skipped=0    rescued=0    ignored=0
 
    
ERROR: 
```

I see that molecule is not generating /tmp/molecule/ansible/default/instance_config.yml (no such file) nor configure ssh connection /tmp/molecule/ansible/default/inventory:
```
# Molecule managed

---
all:
  hosts:
    centos7: &id001 {}
  vars:
    molecule_ephemeral_directory: '{{ lookup(''env'', ''MOLECULE_EPHEMERAL_DIRECTORY'')
      }}'
    molecule_file: '{{ lookup(''env'', ''MOLECULE_FILE'') }}'
    molecule_instance_config: '{{ lookup(''env'', ''MOLECULE_INSTANCE_CONFIG'') }}'
    molecule_scenario_directory: '{{ lookup(''env'', ''MOLECULE_SCENARIO_DIRECTORY'')
      }}'
    molecule_yml: '{{ lookup(''file'', molecule_file) | molecule_from_yaml }}'
ungrouped:
  hosts:
    centos7: *id001
  vars: {}
```

Here is what I get when try to login:
```
$ molecule login
--> Validating schema /home/user/molecule/ansible/molecule/default/molecule.yml.
Validation completed successfully.
Traceback (most recent call last):
  File "/home/user/Env/ansible/bin/molecule", line 10, in <module>
    sys.exit(main())
  File "/home/user/Env/ansible/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/user/Env/ansible/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/user/Env/ansible/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/user/Env/ansible/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/user/Env/ansible/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/user/Env/ansible/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/user/Env/ansible/lib/python2.7/site-packages/molecule/command/login.py", line 182, in login
    base.execute_subcommand(scenario.config, subcommand)
  File "/home/user/Env/ansible/lib/python2.7/site-packages/molecule/command/base.py", line 102, in execute_subcommand
    return command(config).execute()
  File "/home/user/Env/ansible/lib/python2.7/site-packages/molecule/command/login.py", line 103, in execute
    self._get_login(hostname)
  File "/home/user/Env/ansible/lib/python2.7/site-packages/molecule/command/login.py", line 139, in _get_login
    login_options = self._config.driver.login_options(hostname)
  File "/home/user/Env/ansible/lib/python2.7/site-packages/molecule/driver/vagrant.py", line 175, in login_options
    return util.merge_dicts(d, self._get_instance_config(instance_name))
  File "/home/user/Env/ansible/lib/python2.7/site-packages/molecule/driver/vagrant.py", line 209, in _get_instance_config
    self._config.driver.instance_config)
  File "/home/user/Env/ansible/lib/python2.7/site-packages/molecule/util.py", line 189, in safe_load_file
    with open_file(filename) as stream:
  File "/usr/lib64/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/home/user/Env/ansible/lib/python2.7/site-packages/molecule/util.py", line 202, in open_file
    with open(filename, mode) as stream:
IOError: [Errno 2] No such file or directory: '/tmp/molecule/ansible/default/instance_config.yml'
```

Login with vagrant ssh is ok:

```
$ vagrant global-status --prune
id       name    provider   state   directory                           
------------------------------------------------------------------------
e8fd622  centos7 virtualbox running /tmp/molecule/ansible/default
$ vagrant ssh e8fd622
[vagrant@centos7 ~]$
```

Used configuration:
molecule.yml
```
---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: virtualbox
    options:
      memory: 512
      cpus: 1
lint:
  name: yamllint
platforms:
  - name: centos7
    box: centos/7
provisioner:
  name: ansible
  lint:
    name: ansible-lint
verifier:
  name: testinfra
  lint:
    name: flake8
```

create.yml
```
---
- hosts: localhost
  connection: local
  tasks:
    - name: Create instances
      molecule_vagrant:
        instance_name: "centos7"
        platform_box: centos/7
        state: up
```

destroy.yml
```
---
- hosts: localhost
  connection: local
  tasks:
    - name: Destroy instances
      molecule_vagrant:
        instance_name: "centos7"
        platform_box: centos/7
        state: destroy
```

Used versions:
* Fedora 29/30
* Vagrant 2.2.4
* VirtualBox 6.0.8
* testinfra 1.19.0
```
ansible 2.8.0
  config file = None
  configured module search path = [u'/home/user/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/user/Env/ansible/lib/python2.7/site-packages/ansible
  executable location = /home/user/Env/ansible/bin/ansible
  python version = 2.7.16 (default, Apr 30 2019, 15:54:43) [GCC 9.0.1 20190312 (Red Hat 9.0.1-0.10)]
molecule, version 2.20.1
```

Molecule installation method (one of):

- pip

Ansible installation method (one of):

- pip

# Desired Behavior

Working ssh connection.

# Actual Behaviour

```
Failed to connect to the host via ssh: ssh: Could not resolve hostname centos7: Name or service not known
```

**Comment by decentral1se** [comment] 2019-05-29 09:34
Duplicate of https://github.com/ansible/molecule/issues/2069, I think.

**Comment by SergeyBear** [comment] 2019-05-29 09:58
In #2069 'molecule login' is working, but in my case it is not and ssh connection is not generating.

**Comment by decentral1se** [comment] 2019-05-29 10:47
Ah, OK, I could not tell before you updated the description on the issue.

My first inclination is to ask if you already have a `/tmp/molecule/` at all? These kind of bugs are usually due to some sort of state mixup and I typically recommend to run a `rm -rf /tmp/molecule/`, use the underlying driver CLI to clean up any instances and try to run `molecule create` again.

So, it seems that Molecule is failing to generate some files it needs to build the SSH connection details before running the SSH. We should probably report that earlier when running `molecule create`.

> IOError: [Errno 2] No such file or directory: '/tmp/molecule/ansible/default/instance_config.yml'

We should handle this more gracefully when those files are missing on `molecule login`.

**Comment by SergeyBear** [comment] 2019-05-29 11:10
Here is what full run, but I cannot see anything else :+1: -(
```
$ vagrant global-status --prune
id       name   provider state  directory                           
--------------------------------------------------------------------
There are no active Vagrant environments on this computer! Or,
you haven't destroyed and recreated Vagrant environments that were
started with an older version of Vagrant.
$ rm -rf /tmp/molecule/
$ molecule test
--> Validating schema /home/user/molecule/ansible/molecule/default/molecule.yml.
Validation completed successfully.
--> Test matrix
    
└── default
    ├── lint
    ├── cleanup
    ├── destroy
    ├── dependency
    ├── syntax
    ├── create
    ├── prepare
    ├── converge
    ├── idempotence
    ├── side_effect
    ├── verify
    ├── cleanup
    └── destroy
    
--> Scenario: 'default'
--> Action: 'lint'
--> Executing Yamllint on files found in /home/user/molecule/ansible/...
Lint completed successfully.
--> Executing Flake8 on files found in /home/user/molecule/ansible/molecule/default/tests/...
Lint completed successfully.
--> Executing Ansible Lint on /home/user/molecule/ansible/molecule/default/playbook.yml...
Lint completed successfully.
--> Scenario: 'default'
--> Action: 'cleanup'
Skipping, cleanup playbook not configured.
--> Scenario: 'default'
--> Action: 'destroy'
    
    PLAY [localhost] ***************************************************************
    
    TASK [Gathering Facts] *********************************************************
    ok: [localhost]
    
    TASK [Destroy instances] *******************************************************
    ok: [localhost]
    
    PLAY RECAP *********************************************************************
    localhost                  : ok=2    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
    
    
--> Scenario: 'default'
--> Action: 'dependency'
Skipping, missing the requirements file.
--> Scenario: 'default'
--> Action: 'syntax'
    
    playbook: /home/user/molecule/ansible/molecule/default/playbook.yml
    
--> Scenario: 'default'
--> Action: 'create'
    
    PLAY [localhost] ***************************************************************
    
    TASK [Gathering Facts] *********************************************************
    ok: [localhost]
    
    TASK [Create instances] ********************************************************
    changed: [localhost]
    
    PLAY RECAP *********************************************************************
    localhost                  : ok=2    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
    
    
--> Scenario: 'default'
--> Action: 'prepare'
    
    PLAY [Prepare] *****************************************************************
    
    TASK [Install python for Ansible] **********************************************
    fatal: [centos7]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh: ssh: Could not resolve hostname centos7: Name or service not known", "unreachable": true}
    
    PLAY RECAP *********************************************************************
    centos7                    : ok=0    changed=0    unreachable=1    failed=0    skipped=0    rescued=0    ignored=0
    
    
ERROR: 
An error occurred during the test sequence action: 'prepare'. Cleaning up.
--> Scenario: 'default'
--> Action: 'destroy'
    
    PLAY [localhost] ***************************************************************
    
    TASK [Gathering Facts] *********************************************************
    ok: [localhost]
    
    TASK [Destroy instances] *******************************************************
    changed: [localhost]
    
    PLAY RECAP *********************************************************************
    localhost                  : ok=2    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
```

**Comment by SergeyBear** [comment] 2019-05-29 11:14
Here is a Vagrant log during that test, but there is no problems in it.

/tmp/molecule/ansible/default/vagrant-centos7.err
```
### 2019-05-29 14:05:58 ###
### 2019-05-29 14:05:58 ###
```
/tmp/molecule/ansible/default/vagrant-centos7.out
```
### 2019-05-29 14:05:19 ###
Bringing machine 'centos7' up with 'virtualbox' provider...
==> centos7: Cloning VM...

.[K==> centos7: Matching MAC address for NAT networking...
==> centos7: Checking if box 'centos/7' version '1902.01' is up to date...
==> centos7: Setting the name of the VM: default_centos7_1559127925880_2483
==> centos7: Clearing any previously set network interfaces...
==> centos7: Preparing network interfaces based on configuration...
    centos7: Adapter 1: nat
==> centos7: Forwarding ports...
    centos7: 22 (guest) => 2222 (host) (adapter 1)
==> centos7: Running 'pre-boot' VM customizations...
==> centos7: Booting VM...
==> centos7: Waiting for machine to boot. This may take a few minutes...
    centos7: SSH address: 127.0.0.1:2222
    centos7: SSH username: vagrant
    centos7: SSH auth method: private key
    centos7:
    centos7: Vagrant insecure key detected. Vagrant will automatically replace
    centos7: this with a newly generated keypair for better security.
    centos7:
    centos7: Inserting generated public key within guest...
    centos7: Removing insecure key from the guest if it's present...
    centos7: Key inserted! Disconnecting and reconnecting using new SSH key...
==> centos7: Machine booted and ready!
==> centos7: Checking for guest additions in VM...
    centos7: No guest additions were detected on the base box for this VM! Guest
    centos7: additions are required for forwarded ports, shared folders, host only
    centos7: networking, and more. If SSH fails on this machine, please install
    centos7: the guest additions and repackage the box to continue.
    centos7:
    centos7: This is not an error message; everything may continue to work properly,
    centos7: in which case you may ignore this message.
==> centos7: Setting hostname...
==> centos7: Machine not provisioned because `--no-provision` is specified.
### 2019-05-29 14:05:58 ###
==> centos7: Forcing shutdown of VM...
==> centos7: Destroying VM and associated drives...
```

**Comment by SergeyBear** [comment] 2019-05-29 11:34
I also tried 'molecule --debug test', but it is very verbose and cannot see any errors except:
```
Failed to connect to the host via ssh: ssh: Could not resolve hostname centos7: Name or service not known
```

**Comment by SergeyBear** [comment] 2019-05-29 13:19
Just tried to reproduce with molecule 2.19.0 and ansible 2.7.10 - same result...

**Comment by decentral1se** [comment] 2019-05-30 09:00
Thanks for digging into it! I think I've pretty much just reproduced this now over at https://travis-ci.com/ansible/molecule/jobs/204149938#L671 (new driver implementation). It seems the configuration file generation is somehow broken ...

**Comment by SergeyBear** [comment] 2019-05-31 15:48
Can I help to reproduce error by providing additional debug info/configs or something?

**Comment by SergeyBear** [comment] 2019-07-01 16:13
After digging this issue I found that config example from documentaion has missing part that populates created instance config. Thats why inventory was an empty dict and connection to vm unavailable.

The fix was as easy as replacing create.yaml and destroy.yaml (from  https://molecule.readthedocs.io/en/stable/configuration.html#molecule-vagrant-module) with
https://raw.githubusercontent.com/ansible/molecule/2.20.1/molecule/provisioner/ansible/playbooks/vagrant/create.yml
https://raw.githubusercontent.com/ansible/molecule/2.20.1/molecule/provisioner/ansible/playbooks/vagrant/destroy.yml
and everithing started to work properly.

I was forced to spent a lot of time to understant how molecule works under the hood to fix this issue.
PLEASE fix documentation with working example!!!

**Comment by decentral1se** [comment] 2019-07-01 16:16
Happily accepting documentation patches.

**Comment by SergeyBear** [comment] 2019-07-02 16:34
Dig some code and found that create.yml and destroy.yml are not needed at all (actually if they present and wrong then this issue appear). After removing them all started to work like with correct create.yml and destroy.yml from repo.

I'll think how to better describe this in documentation...

**Comment by SergeyBear** [comment] 2019-07-03 07:52
Correct me if I'm wrong - the main problem of using vagrant is that molecule cannot know instance ssh port/host/key because vagrant generates them while creating instance. So ansible create.yml must create instance_config.yml and fill it with returned by vagrant ssh connection params. After file is created molecule reads this ssh connection params.

**Comment by SergeyBear** [comment] 2019-07-03 10:56
I think adding notice in [configuration.rst](ansible/molecule/blob/master/docs/configuration.rst) would be enough.
If its ok, please push to docs. Thank you!

```diff
--- configuration.rst	2019-07-03 13:46:35.181851601 +0300
+++ configuration-new.rst	2019-07-03 13:46:15.017946695 +0300
@@ -153,6 +153,16 @@
 * Parallels
 * Libvirt (requires vagrant-libvirt plugin)
 
+.. note::
+
+    Molecule already bundled with [create.yml](https://github.com/ansible/molecule/blob/master/molecule/provisioner/ansible/playbooks/vagrant/create.yml) and [destroy.yml](https://github.com/ansible/molecule/blob/master/molecule/provisioner/ansible/playbooks/vagrant/destroy.yml) playbooks, so you don't need to create them manually.
+    
+    Customizing ``create.yml`` and ``destroy.yml`` is not recommended, please, use ``prepare.yml`` instead.
+
+.. important::
+
+   Examples below are NOT complete playbooks and does not contain some important parts like ``populate instance config`` and others.
+
 Create instances.
 
 .. code-block:: yaml
```

**Comment by ssbarnea** [comment] 2020-01-14 12:22
Molecule Vagrant driver was moved to https://github.com/pycontribs/molecule-vagrant/issues and if this issue is still valid, please raise a ticket there. Thanks.

**Closed by ssbarnea** 2020-01-14 12:22 UTC
Labels: bug, vagrant
