### ISSUE TITLE
Skip dependencies linting

### ISSUE THREAD

**Issue by beenje** [ansible/molecule#1908] opened 2019-04-08 11:22 UTC
# Issue Type

- Feature request

# Molecule and Ansible details

```
ansible --version && molecule --version
ansible 2.7.9
  config file = /Users/benjaminbertrand/.ansible.cfg
  configured module search path = [u'/Users/benjaminbertrand/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/benjaminbertrand/miniconda3/envs/molecule220/lib/python2.7/site-packages/ansible
  executable location = /Users/benjaminbertrand/miniconda3/envs/molecule220/bin/ansible
  python version = 2.7.15 | packaged by conda-forge | (default, Feb 27 2019, 20:44:16) [GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)]
molecule, version 2.20.0
```

Molecule installation method (one of):

- pip

Ansible installation method (one of):

- pip

# Desired Behavior

We use one git repository per role.
If a role has some dependencies, running `molecule lint` in a role also checks the other roles that are in the parent directory. That shouldn't be the case. The dependencies should not be checked.

This is an issue because on our gitlab-runners, all projects are cloned in the same directory and linting can fail due to some old roles in the working directory.

I think it's easier to explain with an example:

## How to reproduce the issue

If we take a role_b that depends on role_a:
```
$ cat role_b/meta/main.yml
---
dependencies:
  - role_a

$ cat $ cat role_b/molecule/default/requirements.yml
---
- src: git+https://github.com/beenje/role_a.git
```

If we just clone role_b, everything works fine:
```
$ git clone https://github.com/beenje/role_b.git
$ ls
role_b
$ cd role_b
$ molecule lint
--> Action: 'lint'
--> Executing Yamllint on files found in /Users/benjaminbertrand/Dev/ansible/lint/tmp/role_b/...
Lint completed successfully.
Skipping, no tests found.
--> Executing Ansible Lint on /Users/benjaminbertrand/Dev/ansible/lint/tmp/role_b/molecule/default/playbook.yml...
Lint completed successfully.
```

Now if we clone the role_a (which is a dependency of role_b) in the same directory as where role_b is, `molecule lint` in **role_b** will lint role_a as well, which is not what is expected.
```
$ cd ..
$ git clone https://github.com/beenje/role_a.git
$ ls
role_a	role_b
$ cd role_b
$ molecule lint
--> Action: 'lint'
--> Executing Yamllint on files found in /Users/benjaminbertrand/Dev/ansible/lint/tmp/role_b/...
Lint completed successfully.
Skipping, no tests found.
--> Executing Ansible Lint on /Users/benjaminbertrand/Dev/ansible/lint/tmp/role_b/molecule/default/playbook.yml...
    [301] Commands should not change things if nothing needs doing
    /Users/benjaminbertrand/Dev/ansible/lint/tmp/role_a/tasks/main.yml:2
    Task/Handler: task that will raise "yum used in place of yum module"

    [303] yum used in place of yum module
    /Users/benjaminbertrand/Dev/ansible/lint/tmp/role_a/tasks/main.yml:2
    Task/Handler: task that will raise "yum used in place of yum module"
```
The role_a directory should not impact the role_b linting.

I put that as a feature request but it could be seen as a bug.

**Comment by decentral1se** [comment] 2019-04-09 07:22
> also checks the other roles that are in the parent directory.
> This is an issue because on our gitlab-runners, all projects are cloned in the same directory
> if we clone the role_a (which is a dependency of role_b) in the same directory as where role_b is

To clarify: you're installing your dependencies into a different path than your role definitions? The usage of "parent directory" and "same directory" has me confused.

**Comment by beenje** [comment] 2019-04-09 09:14
Trying to clarify:
- we have one git repository per role
- we often clone all git repositories in the same directory (so role_a and role_b are in the same directory)
- the dependencies are always referred as git url (in requirements.yml). `molecule dependency` will download the dependencies from a git repository and install them in molecule $ephemeral_directory.
- the issue is that `molecule lint` will find dependencies that sometimes happen to be in the local filesystem

We don't install dependencies in a specific path. It happens that some roles in the filesystem are dependencies of other roles. But we always use git url for dependencies.

```
# both role_a and role_b are cloned in the same directory
$ ls
role_a  role_b
# If I go inside role_b directory and run "molecule lint", it will find role_a in the parent directory of role_b
$ cd role_b
$ molecule lint
# We never refer to ../role_a in role_b. We use "src: git+https://github.com/beenje/role_a.git" in the requirements.yml
```

Does it make sense?
If you look at the role_a and role_b git repositories mentioned above, you can easily reproduce the issue.

**Comment by blackillzone** [comment] 2019-04-09 09:20
Hello Molecule maintainers, 

We have the same kind of behaviour in our repository. The problem is that the linter executes on all the needed roles of the playbook.yml, if they are in root directory. There is several case when this happen, with role dependencies (I'll reuse role example from initial issue), and it's mainly a problem when you're developing locally (not on CI, as we're always working on a clean directory):

Let's start from a clean folder:

`git clone role_b`

**role_b** depends on **role_a**, so I have a `requirements.yml` in my default scenario, in order to download the dependency:
If I do a `molecule test`, it will do a lint first, and everything will work as expected (the lint is executed only on role_b).

Now, I'm working on **role_a**, and as expected, I'm putting all my roles in the same directory (locally), because it's easier to maintain this way (but each role have it's own git repo).

If I do a `molecule test` on this role, the lint fail (because it's a role which haven't been reworked, since the new ansible-lint update, which molecule 2.20, so I have lint errors on meta.yml):

```yaml
--> Executing Yamllint on files found in /home/fdhaussy/workspace/auchan/ansible/develop/centos7-basics/...
Lint completed successfully.
--> Executing Flake8 on files found in /home/fdhaussy/workspace/auchan/ansible/develop/centos7-basics/molecule/default/tests/...
Lint completed successfully.
--> Executing Ansible Lint on /home/fdhaussy/workspace/auchan/ansible/develop/centos7-basics/molecule/default/playbook.yml...
    [701] No 'galaxy_info' found
    /home/fdhaussy/workspace/auchan/ansible/develop/centos7-basics/meta/main.yml:1
    {'meta/main.yml': {'__file__': u'/home/fdhaussy/workspace/auchan/ansible/develop/centos7-basics/meta/main.yml', u'dependencies': [], '__line__': 1}}
```

So now, If I'm working again on **role_b**, the lint will fail in the following case:
- If I'm only doing a `molecule lint`
- If I'm only doing a `molecule test`

I guess the origin of this is the monolith repo: https://molecule.readthedocs.io/en/stable/examples.html#monolith-repo

To make it work locally, I need to do a `molecule dependency` first, before the `molecule lint`, and this way, the linter avoid to execute on role dependency.

To make it work with `molecule test`, I need to alter the default test sequence, in order to put dependency in first, instead of lint.

```yaml
scenario:
  name: default
  test_sequence:
    - dependency
    - lint
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - converge
    - idempotence
    - side_effect
    - verify
    - cleanup
    - destroy
```

So, I think the problem comes from dependency, which are managed differently by the lint step, if they come from a requirements.yml, or from the monolith repo.

In my opinion, they both should work the same way, whatever final decision you took:
- Lint only on the current role (which is the best solution, in my opinion)
- Lint on the role, and all it's dependencies

I hope it was explicit enough.

**Comment by beenje** [comment] 2019-04-09 11:29
@blackillzone summarised well our issue.
We used the `molecule dependency` trick in the past before running `molecule test` to avoid this problem. But it doesn't work anymore with molecule 2.20 (I'm not sure in which version it stopped working).

**Comment by seandst** [comment] 2019-04-09 20:11
> We used the `molecule dependency` trick in the past before running `molecule test` to avoid this problem. But it doesn't work anymore with molecule 2.20 (I'm not sure in which version it stopped working).

A [fix](https://github.com/ansible/molecule/pull/1739) for this just got merged, so `test` will soon run `dependency` before steps that run playbooks, allowing you to more safely depend on roles for use in any playbook (e.g. `create`, `prepare`, `converge`, `side-effect`, `cleanup`, `destroy`, etc). It still runs `lint` before `dependency` so that `lint` fails quickly, but it won't clean up dependencies unless `destroy` was called, and then it won't do the clean up until *after* the entire sequence runs.

This should be working now with the latest master, but I'm not entirely sure which version it's going to land in yet. If you're using master, though, and want to run `lint` after `dependency`, you can either customize the sequences in `molecule.yml`, or explicitly call `dependency` before running `test`/`lint`.

Dependencies installed via the `dependency` step shouldn't end up in a place that the `lint` step will find them; I'm not sure if the changes I've mentioned address the originally reported issue or not.

**Comment by blackillzone** [comment] 2019-04-16 08:19
I'm not sure it will fix the problem. As you're mentioning it, the `dependency` step place the dependencies correctly (so the `lint` step don't act on all the dependencies).

The problem comes when you have a root folder with all your Ansible roles, and launch the `test` from one on those roles, with playbook dependencies on other roles. Then, the `lint` applied on all the roles present in the root folder.

For example:

```
rootFolder/role1
rootFolder/role2
rootFolder/role3
```

If I'm trying to test role3, with the following playbook (in the `default` scenario):

```yaml
---
# default playbook used by molecule
- hosts: all
  become: true
  roles:
    - role: role1
    - role: role2

- hosts: all
  become: true
  roles:
    - role: role3
```

And if I didn't previously run `converge` or `dependency` (so any related dependencies that I would have in my `requirements.yml` aren't cached), then doing a simple `lint` or `test` would fail, because it scrap all the roles from the rootFolder (as it was by default using the [monolith repo](https://molecule.readthedocs.io/en/stable/examples.html#monolith-repo) pattern). And as those roles don't pass those lint tests (for x reasons), I can't go any further.

The problem is that the `lint` step pass on all roles from the provided playbook, if they are present in the rootFolder (if the rootFolder is empty, and with only `role3`, then there isn't any problems).

It's a bit hard to explain the behaviour only by text, so hope it's clear enough ^^.

If I have some time, I may give you an example with two roles, and a pipeline on a public CI, to show an example.

**Comment by ssbarnea** [comment] 2019-08-09 10:31
I encountered a very similar issue which mainly uncovered that dependency must be run before lint, ad dependency can install roles/modules without which linting could fail. 

If you put your dependencies correctly their entire code would not be included in the linting *but* if you do other inclusions, it would be up to you to add exclude file patterns for the linters involved.

**Closed** 2019-08-21 11:20 UTC
Labels: enhancement, pr-available
