### ISSUE TITLE
development: molecule should have only one linting tox target

### ISSUE THREAD

**Issue by ssbarnea** [ansible/molecule#1584] opened 2018-11-12 12:00 UTC
# Issue Type

- Bug report

# Desired Behavior

Be able to run all linting jobs with a single tox target, like "tox -e lint"

Linting should happen on a single python interpreter, but this has to be a python3 one because py2 versions have smaller checking ability than their python3 versions (even on the same linter version).

If approved, I can easily raise a PR that would:
* consolidate "format-check" into "lint" environment
* consolidate py*-lint into a single "lint" that has basepython=python3
* update ``travis.yaml``

# Actual Behaviour

Now linting is spread across 4 tox targets making hard for a developer to lint his change before making a contribution. 

Current setup is also high-maintenance as if we add new linter or swap one we may be forced to add/remove the list of targets. 

Current setup is also resource intensive as it would take 4X amount the space needed for linting because tox created new virtualenvs for each of them, when in fact there is no real need to isolated environments between different linters.

This is related to #1546 but it covers one specific area, making it easier to implement.

**Comment by webknjaz** [comment] 2018-11-12 12:20
`format-check` shall remain separate. It's easier to reason about it when looking at Travis CI jobs. It doesn't take a lot of time to complete.

**Comment by webknjaz** [comment] 2018-11-18 11:44
Duplicate of #1596

**Closed by webknjaz** 2018-11-18 11:44 UTC
