### ISSUE TITLE
Mitogen integration

### ISSUE THREAD

**Issue by k4ch0** [ansible/molecule#2195] opened 2019-08-03 01:01 UTC
# Issue Type

- Feature request

# Molecule and Ansible details

```
ansible --version && molecule --version

ansible 2.7.0
  config file = /home/luis/ansible.cfg
  configured module search path = ['/home/luis/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/luis/.virtualenvs/python3.6/lib/python3.6/site-packages/ansible
  executable location = /home/luis/.virtualenvs/python3.6/bin/ansible
  python version = 3.6.7 (default, Oct 21 2018, 04:56:05) [GCC 5.4.0 20160609]
molecule, version 2.20.1

```

Molecule installation method (one of):

- pip

Ansible installation method (one of):

- pip

# Desired Behavior

Integrate mitogen directly on Molecule.

**Comment by ssbarnea** [comment] 2019-08-03 12:15
I don't think that any change is needed to enable use of mitogen, if you configure ansible environments right.

**Comment by dw** [comment] 2019-08-03 18:14
There is unfortunately apparently some bug I haven't gotten around to sorting yet ( https://github.com/dw/mitogen/issues/467 ), even though @dsgnr was kind enough to create a reproduction for me.

Is anyone here having trouble with Molecule? I admit to not having used it yet

**Comment by decentral1se** [comment] 2019-08-03 21:56
Sounds cool, didn't know about this one! It would be cool to speed up execution time because Molecule has to do a lot of work and it is often seen as quite slow. If it goes like @ssbarnea says then we can add a config/option/env var to arrange it all internally to use mitogen.

**Comment by dw** [comment] 2019-08-03 22:01
I'm not sure how much integration is really needed -- for example in the reproduction, any Mitogen cutpaste seems to be entirely limited to a few lines in this file: https://github.com/dsgnr/mitogen-molecule-test/blob/master/molecule/default/molecule.yml

Longer term, AFAIK Mazer will have / already has support for packaging up strategy plugins. The existing Galaxy manifest was not flexible enough for it (again AFAIK). Perhaps installing Mitogen is just a specific instance of the general problem of depending on stuff from Galaxy/mazer. (Mitogen does not support this yet, but if it's possible, once mazer is popular it's the obvious solution for packaging in future)

**Comment by k4ch0** [comment] 2019-08-11 04:51
Hi,

My suggestion is to integrate it for an easy usage on CI/CD.
I'm trying to use it on circleci with the changes described on: https://github.com/dsgnr/mitogen-molecule-test/blob/master/molecule/default/molecule.yml

But it is failing, that is why I prefer to ask for a easy integration.

**Comment by ssbarnea** [comment] 2019-08-11 09:20
I will close this because no core is willing to work on doing this but if you find a way to add this as an **optional** feature, make a PR and we can watch it and see how reliable it is. If it proves decently reliable, we can add this feature.

Still, if Molecule own testing would not pass with mitogen enabled, I will not accept the PR.

**Closed by ssbarnea** 2019-08-11 09:20 UTC
Labels: enhancement
