### ISSUE TITLE
Molecule and docker images

### ISSUE THREAD

**Issue by till** [ansible/molecule#2304] opened 2019-09-18 09:16 UTC
# Issue Type

- Bug report

# Molecule and Ansible details

```
$ ansible --version && molecule --version
ansible 2.6.3
  config file = None
  configured module search path = [u'/Users/till/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.16 (default, Sep  2 2019, 11:59:44) [GCC 4.2.1 Compatible Apple LLVM 10.0.1 (clang-1001.0.46.4)]
molecule, version 2.20.1
```

Molecule installation method (one of):

- homebrew

Ansible installation method (one of):

- OS package (homebrew)

Detail any linters or test runners used:

# Desired Behavior

Trying to run a molecule scenario for a role locally. I configured a very barebones setup, using the Docker driver and a `centos:7` Docker image.

Here's my `molecule.yml`:

```
---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: instance
    image: centos:7
provisioner:
  name: ansible
  lint:
    name: ansible-lint
verifier:
  name: testinfra
  lint:
    name: flake8
```

I haven't added any tests yet, I just did `init` yesterday and struggled to run the skeleton.

```
$ molecule init scenario --role-name=my-role --driver-name=docker
```

# Actual Behaviour

```
$ molecule --debug converge
--> Validating schema /path/my-role/molecule/default/molecule.yml.
Validation completed successfully.
--> Test matrix
    
└── default
    ├── dependency
    ├── create
    ├── prepare
    └── converge
    
--> Scenario: 'default'
--> Action: 'dependency'
Skipping, missing the requirements file.
--> Scenario: 'default'
--> Action: 'create'
DEBUG: ANSIBLE ENVIRONMENT
---
ANSIBLE_CONFIG: /var/folders/yg/_vjn6wys2pxfcvwbd84r2bf00000gn/T/molecule/my-role/default/ansible.cfg
ANSIBLE_FILTER_PLUGINS: /usr/local/Cellar/molecule/2.20.1_1/libexec/lib/python2.7/site-packages/molecule/provisioner/ansible/plugins/filters:/var/folders/yg/_vjn6wys2pxfcvwbd84r2bf00000gn/T/molecule/my-role/default/plugins/filters:/path/my-role/plugins/filters
ANSIBLE_LIBRARY: /usr/local/Cellar/molecule/2.20.1_1/libexec/lib/python2.7/site-packages/molecule/provisioner/ansible/plugins/libraries:/var/folders/yg/_vjn6wys2pxfcvwbd84r2bf00000gn/T/molecule/my-role/default/library:/path/my-role/library
ANSIBLE_ROLES_PATH: /var/folders/yg/_vjn6wys2pxfcvwbd84r2bf00000gn/T/molecule/my-role/default/roles:/path
ANSIBLE_VAULT_PASSWORD_FILE:

DEBUG: MOLECULE ENVIRONMENT
---
MOLECULE_DEBUG: 'True'
MOLECULE_DEPENDENCY_NAME: galaxy
MOLECULE_DRIVER_NAME: docker
MOLECULE_ENV_FILE: /path/my-role/.env.yml
MOLECULE_EPHEMERAL_DIRECTORY: /var/folders/yg/_vjn6wys2pxfcvwbd84r2bf00000gn/T/molecule/my-role/default
MOLECULE_FILE: /path/my-role/molecule/default/molecule.yml
MOLECULE_INSTANCE_CONFIG: /var/folders/yg/_vjn6wys2pxfcvwbd84r2bf00000gn/T/molecule/my-role/default/instance_config.yml
MOLECULE_INVENTORY_FILE: /var/folders/yg/_vjn6wys2pxfcvwbd84r2bf00000gn/T/molecule/my-role/default/inventory/ansible_inventory.yml
MOLECULE_LINT_NAME: yamllint
MOLECULE_PROJECT_DIRECTORY: /path/my-role
MOLECULE_PROVISIONER_LINT_NAME: ansible-lint
MOLECULE_PROVISIONER_NAME: ansible
MOLECULE_SCENARIO_DIRECTORY: /path/my-role/molecule/default
MOLECULE_SCENARIO_NAME: default
MOLECULE_VERIFIER_LINT_NAME: flake8
MOLECULE_VERIFIER_NAME: testinfra
MOLECULE_VERIFIER_TEST_DIRECTORY: /path/my-role/molecule/default/tests

DEBUG: SHELL REPLAY
ANSIBLE_CONFIG=/var/folders/yg/_vjn6wys2pxfcvwbd84r2bf00000gn/T/molecule/my-role/default/ansible.cfg ANSIBLE_FILTER_PLUGINS=/usr/local/Cellar/molecule/2.20.1_1/libexec/lib/python2.7/site-packages/molecule/provisioner/ansible/plugins/filters:/var/folders/yg/_vjn6wys2pxfcvwbd84r2bf00000gn/T/molecule/my-role/default/plugins/filters:/path/my-role/plugins/filters ANSIBLE_LIBRARY=/usr/local/Cellar/molecule/2.20.1_1/libexec/lib/python2.7/site-packages/molecule/provisioner/ansible/plugins/libraries:/var/folders/yg/_vjn6wys2pxfcvwbd84r2bf00000gn/T/molecule/my-role/default/library:/path/my-role/library ANSIBLE_ROLES_PATH=/var/folders/yg/_vjn6wys2pxfcvwbd84r2bf00000gn/T/molecule/my-role/default/roles:/path ANSIBLE_VAULT_PASSWORD_FILE=/Users/till/.vault_pass.txt MOLECULE_DEBUG=True MOLECULE_DEPENDENCY_NAME=galaxy MOLECULE_DRIVER_NAME=docker MOLECULE_ENV_FILE=/path/my-role/.env.yml MOLECULE_EPHEMERAL_DIRECTORY=/var/folders/yg/_vjn6wys2pxfcvwbd84r2bf00000gn/T/molecule/my-role/default MOLECULE_FILE=/path/my-role/molecule/default/molecule.yml MOLECULE_INSTANCE_CONFIG=/var/folders/yg/_vjn6wys2pxfcvwbd84r2bf00000gn/T/molecule/my-role/default/instance_config.yml MOLECULE_INVENTORY_FILE=/var/folders/yg/_vjn6wys2pxfcvwbd84r2bf00000gn/T/molecule/my-role/default/inventory/ansible_inventory.yml MOLECULE_LINT_NAME=yamllint MOLECULE_PROJECT_DIRECTORY=/path/my-role MOLECULE_PROVISIONER_LINT_NAME=ansible-lint MOLECULE_PROVISIONER_NAME=ansible MOLECULE_SCENARIO_DIRECTORY=/path/my-role/molecule/default MOLECULE_SCENARIO_NAME=default MOLECULE_VERIFIER_LINT_NAME=flake8 MOLECULE_VERIFIER_NAME=testinfra MOLECULE_VERIFIER_TEST_DIRECTORY=/path/my-role/molecule/default/tests

DEBUG: COMMAND
/usr/local/bin/ansible-playbook --skip-tags=molecule-notest,notest --inventory=/var/folders/yg/_vjn6wys2pxfcvwbd84r2bf00000gn/T/molecule/my-role/default/inventory --diff /usr/local/Cellar/molecule/2.20.1_1/libexec/lib/python2.7/site-packages/molecule/provisioner/ansible/playbooks/docker/create.yml -vvv

    ansible-playbook 2.6.3
      config file = /var/folders/yg/_vjn6wys2pxfcvwbd84r2bf00000gn/T/molecule//path/my-role/default/ansible.cfg
      configured module search path = [u'/usr/local/Cellar/molecule/2.20.1_1/libexec/lib/python2.7/site-packages/molecule/provisioner/ansible/plugins/libraries', u'/var/folders/yg/_vjn6wys2pxfcvwbd84r2bf00000gn/T/molecule/my-role/default/library', u'/path/my-role/library']
      ansible python module location = /usr/local/lib/python2.7/site-packages/ansible
      executable location = /usr/local/bin/ansible-playbook
      python version = 2.7.16 (default, Sep  2 2019, 11:59:44) [GCC 4.2.1 Compatible Apple LLVM 10.0.1 (clang-1001.0.46.4)]
    Using /var/folders/yg/_vjn6wys2pxfcvwbd84r2bf00000gn/T/molecule/my-role/default/ansible.cfg as config file
    Parsed /var/folders/yg/_vjn6wys2pxfcvwbd84r2bf00000gn/T/molecule/my-role/default/inventory/ansible_inventory.yml inventory source with yaml plugin
    
    PLAYBOOK: create.yml ***********************************************************
    1 plays in /usr/local/Cellar/molecule/2.20.1_1/libexec/lib/python2.7/site-packages/molecule/provisioner/ansible/playbooks/docker/create.yml
    
    PLAY [Create] ******************************************************************
    META: ran handlers
    
    TASK [Log into a Docker registry] **********************************************
    task path: /usr/local/Cellar/molecule/2.20.1_1/libexec/lib/python2.7/site-packages/molecule/provisioner/ansible/playbooks/docker/create.yml:8
    fatal: [localhost]: FAILED! => {
        "censored": "the output has been hidden due to the fact that 'no_log: true' was specified for this result"
    }
    
    PLAY RECAP *********************************************************************
    localhost                  : ok=0    changed=0    unreachable=0    failed=1   
    
ERROR:
```

I can't for the live of me figure out why it's trying to log into a Docker registry.

I also tried to `pip install docker` as suggested on similar tickets, to no avail.

**Comment by till** [comment] 2019-09-18 09:24
I did a quick test ran the following:

```
$ brew remove molecule
...
$ pip install molecule
...
$ pip install molecule[docker]
...
```

Then edited `create.yml` and forced `no_log: false` (that part also doesn't work when I `molecule --debug converge`):

Now the error is as follows:

```
task path: /usr/local/lib/python2.7/site-packages/molecule/provisioner/ansible/playbooks/docker/create.yml:8
    The full traceback is:
    Traceback (most recent call last):
      File "/usr/local/lib/python2.7/site-packages/ansible/executor/task_executor.py", line 97, in run
        items = self._get_loop_items()
      File "/usr/local/lib/python2.7/site-packages/ansible/executor/task_executor.py", line 216, in _get_loop_items
        convert_bare=False)
      File "/usr/local/lib/python2.7/site-packages/ansible/utils/listify.py", line 34, in listify_lookup_plugin_terms
        terms = templar.template(terms.strip(), convert_bare=convert_bare, fail_on_undefined=fail_on_undefined)
      File "/usr/local/lib/python2.7/site-packages/ansible/template/__init__.py", line 479, in template
        disable_lookups=disable_lookups,
      File "/usr/local/lib/python2.7/site-packages/ansible/template/__init__.py", line 691, in do_template
        myenv.filters.update(self._get_filters(myenv.filters))
      File "/usr/local/lib/python2.7/site-packages/ansible/template/__init__.py", line 312, in _get_filters
        for fp in self._filter_loader.all():
      File "/usr/local/lib/python2.7/site-packages/ansible/plugins/loader.py", line 566, in all
        plugins = [p for p in super(Jinja2Loader, self).all(*args, **kwargs)]
      File "/usr/local/lib/python2.7/site-packages/ansible/plugins/loader.py", line 489, in all
        module = self._load_module_source(name, path)
      File "/usr/local/lib/python2.7/site-packages/ansible/plugins/loader.py", line 357, in _load_module_source
        module = imp.load_source(full_name, path, module_file)
      File "/usr/local/lib/python2.7/site-packages/molecule/provisioner/ansible/plugins/filters/molecule_core.py", line 23, in <module>
        from molecule import config
      File "/usr/local/lib/python2.7/site-packages/molecule/config.py", line 24, in <module>
        import anyconfig
      File "/usr/local/lib/python2.7/site-packages/anyconfig/__init__.py", line 20, in <module>
        from .api import (
      File "/usr/local/lib/python2.7/site-packages/anyconfig/api.py", line 77, in <module>
        import anyconfig.backends
      File "/usr/local/lib/python2.7/site-packages/anyconfig/backends.py", line 17, in <module>
        import anyconfig.processors
      File "/usr/local/lib/python2.7/site-packages/anyconfig/processors.py", line 14, in <module>
        import pkg_resources
      File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 79, in <module>
        from . import py31compat
    ImportError: cannot import name py31compat
    
    fatal: [localhost]: FAILED! => {
        "msg": "Unexpected failure during module execution.", 
        "stdout": ""
    }
```

Not a Python dev/expert — it's missing a dependency?

**Comment by dallinb** [comment] 2019-10-03 09:45
I'm also on a Mac and am running fine but I'm also using a virtual environment (as suggested at https://molecule.readthedocs.io/en/stable/installation.html#pip).  In my case I'm using [pyenv](https://github.com/pyenv/pyenv) which _is_ OK to install via Homebrew and then installed a Python-3.6.6 version.

**Comment by ssbarnea** [comment] 2019-10-11 11:47
This may be caused by https://github.com/pypa/pip/issues/7122 but you should also assure that you are using right pip and that `pip check` returns no conflict.

I will close this because nobody was able to replicate your error so far, is almost for sure caused by your local environment.

**Closed by ssbarnea** 2019-10-11 11:47 UTC
Labels: bug

**Comment by till** [comment] 2019-10-12 12:22
@ssbarnea I've moved on to running it all in Docker. I'll remember to `pip check` next time.
